import { BoardShape, GridSize, SchulteMode } from '../types';

export interface PracticePlan {
  id: string;
  level: number; // 1-100
  category: 'vision' | 'executive' | 'reading' | 'cognitive' | 'stroop' | 'endurance';
  title: string;
  subtitle: string;
  tag: string;
  tagColor: string;
  icon: string;
  difficulty: number; // 1-5
  audience: string;
  prescription: string;
  brainTarget: string;
  desc: string;
  targetDuration: string;
  config: {
    size: GridSize;
    shape: BoardShape;
    mode: SchulteMode;
    centerFocusDot: boolean;
  };
  stages: { step: number; name: string; detail: string }[];
}

export const CATEGORIES = [
  { id: 'all', label: '全部' },
  { id: 'vision', label: '广角视野' },
  { id: 'executive', label: '思维切换' },
  { id: 'reading', label: '文字速读' },
  { id: 'cognitive', label: '记忆速算' },
  { id: 'stroop', label: '抗扰追踪' },
  { id: 'endurance', label: '极限耐力' },
];

export const TRAINING_PLANS_100: PracticePlan[] = [
  // =========================================================================
  // 1. 广角视野学院 (L01 - L18)
  // =========================================================================
  {
    id: 'plan-001',
    level: 1,
    category: 'vision',
    title: '3×3 晨间极速唤醒冲刺',
    subtitle: '超低阻力 9 格秒速激活大脑与眼动',
    tag: '极速唤醒',
    tagColor: 'bg-teal-100 text-teal-800 border-teal-300',
    icon: '⚡',
    difficulty: 1,
    audience: '晨起状态低迷 · 开工前 1 分钟提神 · 初学者',
    prescription: '连练 3 次，感受用时从 5 秒突破到 3 秒内的神经提速',
    brainTarget: '极短神经反射弧，点燃初级视皮层兴奋度',
    desc: '3×3 仅 9 个方格，耗时极短无心理负担，是唤醒晨间思维与快速进入心流的最佳跳板。',
    targetDuration: '目标: 3×3 < 3.5 秒',
    config: { size: 3, shape: 'grid', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '一眼尽收全盘', detail: '9 个数字无需大幅转动眼球，几乎在瞬间全部尽收眼底' },
      { step: 2, name: '神经极速反射', detail: '手眼无缝配合，形成如流水般的快速连击' },
      { step: 3, name: '挑战个人极值', detail: '尝试突破个人的 3 秒生理极限大关' },
    ],
  },
  {
    id: 'plan-002',
    level: 2,
    category: 'vision',
    title: '3×3 倒序逆水行舟起跑',
    subtitle: '9格倒数 9→1 · 逆向神经初步点火',
    tag: '逆向小试',
    tagColor: 'bg-teal-100 text-teal-800 border-teal-300',
    icon: '⏳',
    difficulty: 1,
    audience: '顺向思维定势 · 需微量反向思维激活者',
    prescription: '每日 2 组，建立反向计数与瞬间定位联动',
    brainTarget: '短序列反向抑制，初步激活前额叶背外侧皮质',
    desc: '从 9 倒数点击至 1，在极小盘面上体验逆向思维的瞬时反馈。',
    targetDuration: '目标: 3×3 逆序 < 4 秒',
    config: { size: 3, shape: 'grid', mode: 'numbers_desc', centerFocusDot: false },
    stages: [
      { step: 1, name: '逆向心理定势', detail: '由 9 展开逆向心理预期' },
      { step: 2, name: '快速定位小数字', detail: '余光向 3、2、1 个位靠拢' },
      { step: 3, name: '连贯收尾', detail: '形成反向流畅节奏' },
    ],
  },
  {
    id: 'plan-003',
    level: 3,
    category: 'vision',
    title: '4×4 经典进阶过渡方案',
    subtitle: '16 格中型盘面 · 余光自适应舒展',
    tag: '初级进阶',
    tagColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    icon: '🎯',
    difficulty: 2,
    audience: '已熟练 3×3 · 欲平稳提升视野覆盖面积者',
    prescription: '每次练习 3 组，稳定在 12 秒以内',
    brainTarget: '拓展视网膜黄斑中心凹外围感受野',
    desc: '从 9 格平缓过渡到 16 格，让眼睛自如适应更宽阔的数字分布。',
    targetDuration: '目标: 4×4 < 10 秒',
    config: { size: 4, shape: 'grid', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '中央视觉锚定', detail: '保持视线平缓，兼顾四角边缘' },
      { step: 2, name: '分组节奏点选', detail: '1-8 与 9-16 保持节奏平稳' },
      { step: 3, name: '抑制眨眼冲动', detail: '练习过程中尽量减少眨眼与停顿' },
    ],
  },
  {
    id: 'plan-004',
    level: 4,
    category: 'vision',
    title: '4×4 同心圆辐射视野计划',
    subtitle: '同心圆环 · 视觉由内向外扩散搜视',
    tag: '圆环辐射',
    tagColor: 'bg-sky-100 text-sky-800 border-sky-300',
    icon: '🌀',
    difficulty: 2,
    audience: '习惯按横纵扫描 · 易遗漏对角边缘数字人群',
    prescription: '建议练习 2 组，感受目光从近圆向远圆递进扩散',
    brainTarget: '打破水平/竖直惯性，形成同心径向空间广角搜寻通路',
    desc: '打破常规矩形边界，在同心圆形阵列中搜索数字，强化不同距离圈层间的视线过渡。',
    targetDuration: '目标: 4×4 同心圆 < 13 秒',
    config: { size: 4, shape: 'circle', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '内环定位感知', detail: '先将注意聚焦在内圈核心区域，建立空间基准' },
      { step: 2, name: '外环余光搜视', detail: '余光向外圈辐射展开，迅速捕获外围边缘目标' },
      { step: 3, name: '径向流畅流转', detail: '目光在不同同心半径之间平滑过渡，消除卡顿感' },
    ],
  },
  {
    id: 'plan-005',
    level: 5,
    category: 'vision',
    title: '4×4 金字塔层级阶梯扫视',
    subtitle: '金字塔三角 · 逐层拓展扫视宽度',
    tag: '金字塔阵',
    tagColor: 'bg-orange-100 text-orange-800 border-orange-300',
    icon: '🔺',
    difficulty: 3,
    audience: '阅读习惯狭窄 · 希望逐级拓展横向阅读跨度',
    prescription: '每次阅读书籍前练习 2 组，拓宽每行有效识别字数',
    brainTarget: '阶梯式扫视训练，锻炼眼睛自适应不同宽度的视觉跨度',
    desc: '从顶层的狭窄单点逐步过渡到底层的宽广基底，模拟速读中由点及面的扫视拓展。',
    targetDuration: '目标: 4×4 金字塔 < 14 秒',
    config: { size: 4, shape: 'triangle', mode: 'numbers_asc', centerFocusDot: false },
    stages: [
      { step: 1, name: '顶端单点快速起步', detail: '从顶层狭小视野迅速启动注意力' },
      { step: 2, name: '中层横向适度展开', detail: '逐渐适应递增的横向跨度与间距' },
      { step: 3, name: '底层极限视野覆盖', detail: '底层宽广排布下一眼尽收多目标，消除横扫死角' },
    ],
  },
  {
    id: 'plan-006',
    level: 6,
    category: 'vision',
    title: '4×4 散落星象抗对称视野',
    subtitle: '散落无规则分布 · 消除网格依赖',
    tag: '非对称星象',
    tagColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    icon: '✨',
    difficulty: 3,
    audience: '习惯按固定行列死板搜索 · 需提高野外或复杂界面视觉抓取力者',
    prescription: '每周练习 3-4 次，训练对不规则空间散点的瞬间感知',
    brainTarget: '彻底打破横平竖直的行列惯性，建立空间任意方位的无规则检索机制',
    desc: '方块如星辰般不规则散落在盘面上，考验脱离网格辅助下的纯粹周边视野捕捉力。',
    targetDuration: '目标: 4×4 散落 < 15 秒',
    config: { size: 4, shape: 'scatter', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '消除行列预期', detail: '不依赖横竖网格，将视野展开为一个整体无界平面' },
      { step: 2, name: '特征点快速联结', detail: '凭借余光捕捉孤立分散的数字节点' },
      { step: 3, name: '形成空间自由路径', detail: '视线在任意角度自由跃迁，实现高敏度搜查' },
    ],
  },
  {
    id: 'plan-007',
    level: 7,
    category: 'vision',
    title: '标准视野拓展基准方案',
    subtitle: '经典 5×5 飞行员中心红点凝视法',
    tag: '经典常模',
    tagColor: 'bg-amber-100 text-amber-800 border-amber-300',
    icon: '🎯',
    difficulty: 3,
    audience: '周边视野受限 · 习惯频繁跳视眨眼 · 每日专注打卡基石',
    prescription: '建议每日 2-3 组，保持呼吸匀称与视线聚焦',
    brainTarget: '注视中心红点，调动周边余光感知数字分布，减少眼球大幅摆动',
    desc: '注视中心红点，尽量减少眼球大幅频繁扫视，调动周边余光捕捉目标数字。国际心理学界与航天员通用测验。',
    targetDuration: '目标: 5×5 < 25 秒',
    config: { size: 5, shape: 'grid', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '凝视中心红点', detail: '保持视线稳定在棋盘中心红点，放松眼周与肩颈肌肉' },
      { step: 2, name: '调动余光感知', detail: '利用外围视野寻找目标数字，抑制大幅度眼球来回跳跃' },
      { step: 3, name: '保持平稳节奏', detail: '形成连贯的点击节拍，逐步提升感知摄入效率' },
    ],
  },
  {
    id: 'plan-008',
    level: 8,
    category: 'vision',
    title: '5×5 菱形斜角广域视野',
    subtitle: '45° 倾斜对角矩阵 · 空间感知刷新',
    tag: '斜角广域',
    tagColor: 'bg-cyan-100 text-cyan-800 border-cyan-300',
    icon: '💠',
    difficulty: 3,
    audience: '长时间看固定文档表格 · 视觉疲劳发紧的办公族',
    prescription: '午间或傍晚练习 2 组，拉伸对角线视觉神经',
    brainTarget: '激活顶叶后部空间坐标系重置通路',
    desc: '将正方形方格旋转 45 度，四角向外突出，训练深远边角的远端余光抓取能力。',
    targetDuration: '目标: 5×5 菱形 < 28 秒',
    config: { size: 5, shape: 'diamond', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '斜向空间校准', detail: '视线顺应倾斜轴向自然展开' },
      { step: 2, name: '四极顶点捕捉', detail: '留意上下左右尖端孤立数字' },
      { step: 3, name: '斜向连续点击', detail: '保持斜角扫视的高频敏锐' },
    ],
  },
  {
    id: 'plan-009',
    level: 9,
    category: 'vision',
    title: '5×5 爱心轮廓有机视野拓展',
    subtitle: '心形边缘起伏 · 弧线广角周边搜视',
    tag: '异形弧光',
    tagColor: 'bg-rose-100 text-rose-800 border-rose-300',
    icon: '❤️',
    difficulty: 3,
    audience: '审美疲劳 · 喜欢生动有机界面 · 需拓宽弧形边缘视野者',
    prescription: '每日 1-2 组，让眼动沿圆润弧线自然游走',
    brainTarget: '不规则曲线轮廓边界感知与特征提取',
    desc: '心形轮廓自上凹至底尖，边缘曲线柔和起伏，训练眼睛追踪非规则有机边界的能力。',
    targetDuration: '目标: 5×5 爱心 < 26 秒',
    config: { size: 5, shape: 'heart', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '顶部双弧扫查', detail: '迅速扫过爱心上部两侧饱满弧度' },
      { step: 2, name: '中心躯干过渡', detail: '视线平滑回落至中间密集区' },
      { step: 3, name: '底部尖角收官', detail: '在狭窄底端精准完成数字定位' },
    ],
  },
  {
    id: 'plan-010',
    level: 10,
    category: 'vision',
    title: '5×5 五角星芒锐角跳跃',
    subtitle: '星芒尖端放射 · 训练视线大跨度跳视',
    tag: '星芒跳视',
    tagColor: 'bg-amber-100 text-amber-800 border-amber-300',
    icon: '⭐',
    difficulty: 4,
    audience: '眼球肌肉僵硬 · 大幅跳跃视野容易跟丢目标者',
    prescription: '练习时注意深呼吸，让眼球如星光在五个尖角间灵敏跃动',
    brainTarget: '额叶眼动区（FEF）对大幅快速扫视（Saccade）的精准制导',
    desc: '五角星尖端向五个方向放射延伸，训练眼球在极大距离与角度间的高速精准落点。',
    targetDuration: '目标: 5×5 星芒 < 29 秒',
    config: { size: 5, shape: 'star', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '五个尖峰预热', detail: '先确认五个突出尖角的大致分布' },
      { step: 2, name: '大跨距飞跃', detail: '由一个尖端直接跳跃至对向尖端，不失准头' },
      { step: 3, name: '内核心无缝承接', detail: '在星核与尖芒间自由穿梭' },
    ],
  },
  {
    id: 'plan-011',
    level: 11,
    category: 'vision',
    title: '5×5 螺旋星系圆周循迹',
    subtitle: '阿基米德旋涡渐进 · 弧线环视追踪',
    tag: '螺旋轨迹',
    tagColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    icon: '🪐',
    difficulty: 4,
    audience: '阅读跳行漏行 · 需增强连续平滑眼动追随能力者',
    prescription: '每周 3 次，感受螺旋向外扩散的动感韵律',
    brainTarget: '顶下小叶对旋转与弯曲轨迹的空间表征',
    desc: '以中心为起点呈阿基米德螺旋线向外展开，锻炼眼球平滑追随运动（Smooth Pursuit）。',
    targetDuration: '目标: 5×5 螺旋 < 28 秒',
    config: { size: 5, shape: 'spiral', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '内圈旋转起跑', detail: '自核芯沿顺时针/逆时针方向起步' },
      { step: 2, name: '半径递增适应', detail: '随圈层扩大扩大扫视半径' },
      { step: 3, name: '最外环全景锁定', detail: '余光收拢外围边缘零散数字' },
    ],
  },
  {
    id: 'plan-012',
    level: 12,
    category: 'vision',
    title: '5×5 蝶翼双环左右视野均衡',
    subtitle: '莫比乌斯双翼 · 左右半球视野协同',
    tag: '双翼平衡',
    tagColor: 'bg-purple-100 text-purple-800 border-purple-300',
    icon: '🦋',
    difficulty: 4,
    audience: '单侧视觉偏好（习惯偏左或偏右看）· 两眼注意分布不均者',
    prescription: '左右两侧交替搜寻，让左右脑半球均等参与视觉处理',
    brainTarget: '胼胝体跨半球视觉信息高速互通与中缝整合',
    desc: '蝴蝶展翅左右对称双环排布，强迫视线在左翼与右翼之间高频摆荡，消除单侧视野盲点。',
    targetDuration: '目标: 5×5 蝶翼 < 27 秒',
    config: { size: 5, shape: 'butterfly', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '左翼视野展开', detail: '关注左侧扇面节点' },
      { step: 2, name: '中轴无缝穿插', detail: '视线横跨中央脊柱转向右翼' },
      { step: 3, name: '双翼自如联通', detail: '左右交替犹如蝴蝶扇翅般灵动顺畅' },
    ],
  },
  {
    id: 'plan-013',
    level: 13,
    category: 'vision',
    title: '5×5 十字星阵象限扫描',
    subtitle: '经纬四象限骨架 · 强化垂直与横向扫描',
    tag: '十字经纬',
    tagColor: 'bg-blue-100 text-blue-800 border-blue-300',
    icon: '➕',
    difficulty: 3,
    audience: '专业图纸、UI界面或代码审查人员 · 需严谨坐标系扫描者',
    prescription: '每日 2 组，保持沿轴向搜视的精确性',
    brainTarget: '直角坐标系脑内网格细胞与方向调谐神经元强化',
    desc: '沿横轴与纵轴构建十字星阵，对上下左右四象限开展严密的经纬度地毯式排查。',
    targetDuration: '目标: 5×5 十字 < 25 秒',
    config: { size: 5, shape: 'cross', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '四端极点定位', detail: '排查十字最外侧的四个端点' },
      { step: 2, name: '四象限内角搜寻', detail: '扫荡四片凹角内部分布的方格' },
      { step: 3, name: '十字核心汇聚', detail: '中心交汇处形成高密度收盘' },
    ],
  },
  {
    id: 'plan-014',
    level: 14,
    category: 'vision',
    title: '5×5 波浪流线蛇形追踪',
    subtitle: 'S型蜿蜒曲折 · 提升动态眼动流线敏捷度',
    tag: '波浪流线',
    tagColor: 'bg-cyan-100 text-cyan-800 border-cyan-300',
    icon: '〰️',
    difficulty: 3,
    audience: '容易被整齐网格催眠 · 需活化眼动灵活度者',
    prescription: '练习时顺应水流般的蜿蜒波浪，保持轻松眨眼与呼吸',
    brainTarget: '视觉运动区（MT/V5）对曲线动态流场的预测与跟驰',
    desc: '如河流蜿蜒般排布，打破僵化方阵，让目光顺着流线曲率穿梭自如。',
    targetDuration: '目标: 5×5 波浪 < 26 秒',
    config: { size: 5, shape: 'wave', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '顺流起势', detail: '从波浪源头顺势出发' },
      { step: 2, name: '回环拐弯处理', detail: '波峰与波谷转向时保持匀速' },
      { step: 3, name: '流线贯通通关', detail: '全屏连贯如行云流水' },
    ],
  },
  {
    id: 'plan-015',
    level: 15,
    category: 'vision',
    title: '5×5 弯月弧形焦点聚散',
    subtitle: '上弦月牙弯弧 · 中间丰盈两头锐聚',
    tag: '弯月弧影',
    tagColor: 'bg-amber-100 text-amber-800 border-amber-300',
    icon: '🌙',
    difficulty: 3,
    audience: '常感视觉疲劳 · 喜欢静心唯美几何形态者',
    prescription: '睡前或晚自习前练习 1 组，沉淀心神，柔化视线焦距',
    brainTarget: '视网膜密度非均匀适应，从宽幅饱满到细微末梢的平滑缩放',
    desc: '月牙一侧饱满另一侧锐利聚拢，考验视线在非对称厚薄分布间的自适应调节。',
    targetDuration: '目标: 5×5 弯月 < 27 秒',
    config: { size: 5, shape: 'crescent', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '月腹饱满区扫描', detail: '先摄入中间密集丰富的数字' },
      { step: 2, name: '两端尖梢延伸', detail: '目光扫向上下两个弯月尖尖' },
      { step: 3, name: '弧背清润收官', detail: '外弧边缘数字一气呵成' },
    ],
  },
  {
    id: 'plan-016',
    level: 16,
    category: 'vision',
    title: '5×5 溪流卵石自由团簇',
    subtitle: '天然异形有机卵石 · 彻底破除对称依赖',
    tag: '有机卵石',
    tagColor: 'bg-teal-100 text-teal-800 border-teal-300',
    icon: '🪨',
    difficulty: 4,
    audience: '高阶视觉探索者 · 需适应自然真实世界非标视觉场景者',
    prescription: '每周练习 2 次，完全抛弃行列逻辑，凭纯视觉直觉捕获',
    brainTarget: '脱离人工网格先验假定，调动自然场景物体分割神经中枢',
    desc: '如山间清溪中的天然卵石自然团簇散落，每个节点位置有机不一，纯凭敏锐直觉检索。',
    targetDuration: '目标: 5×5 卵石 < 28 秒',
    config: { size: 5, shape: 'irregular', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '全景无边界感知', detail: '不寻找行列，将全盘视作一片自然滩涂' },
      { step: 2, name: '数字形态特征抓取', detail: '凭数字特征与高亮对比直接锁定目标' },
      { step: 3, name: '自由无序连击', detail: '视线如飞鸟点水，灵敏跳点' },
    ],
  },
  {
    id: 'plan-017',
    level: 17,
    category: 'vision',
    title: '6×6 蜂巢错位防隧道视野',
    subtitle: '蜂巢六边形 · 消除斜向视觉死角',
    tag: '蜂巢错位',
    tagColor: 'bg-purple-100 text-purple-800 border-purple-300',
    icon: '🐝',
    difficulty: 4,
    audience: '长时间面对窄屏手机 · 易产生“隧道视野”的重度数码用户',
    prescription: '午间或疲劳时练习 1-2 组，放松眼部肌肉并拓宽余光',
    brainTarget: '非正交蜂窝交错几何，强迫神经重塑对角与斜向扫描',
    desc: '打破传统方形行列，采用六边形蜂窝排布，训练斜向与非对称的扫视反应。',
    targetDuration: '目标: 6×6 蜂巢 < 45 秒',
    config: { size: 6, shape: 'honeycomb', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '适应蜂窝交错', detail: '适应非直线排列的相邻六边形节点' },
      { step: 2, name: '边缘节点排查', detail: '重点留意左右两侧及偏远角落的外围节点' },
      { step: 3, name: '全景宏观扫视', detail: '在密集交错排布中形成宏观全局感' },
    ],
  },
  {
    id: 'plan-018',
    level: 18,
    category: 'vision',
    title: '6×6 广角视野进阶考验',
    subtitle: '36 格正交大盘 · 考验持续宏观视野掌控力',
    tag: '36格进阶',
    tagColor: 'bg-slate-800 text-amber-300 border-slate-700',
    icon: '🔭',
    difficulty: 4,
    audience: '5×5 稳定在 20 秒以内 · 欲挑战更广视域的高手',
    prescription: '每周练习 3-4 次，感受 36 个数字在视野中的大纵深分布',
    brainTarget: '前额叶与顶叶联合注意网络对密集空间信息流的高负荷处理',
    desc: '由 25 格跃升至 36 格，数字密度大幅增加，要求始终保持视野外围的敏锐感。',
    targetDuration: '目标: 6×6 < 42 秒',
    config: { size: 6, shape: 'grid', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '1-12 平稳起步', detail: '保持稳定呼吸，建立大盘空间感' },
      { step: 2, name: '13-24 中段维稳', detail: '避免眼动混乱，利用余光分区覆盖' },
      { step: 3, name: '25-36 冲刺收盘', detail: '剩余数字稀疏时迅速连击通关' },
    ],
  },

  // =========================================================================
  // 2. 思维切换与执行控制学院 (L19 - L36)
  // =========================================================================
  {
    id: 'plan-019',
    level: 19,
    category: 'executive',
    title: '4×4 奇数专注抑制筛选',
    subtitle: '仅点击奇数 1,3,5.. · 偶数充当强干扰项',
    tag: '奇数抑制',
    tagColor: 'bg-blue-100 text-blue-800 border-blue-300',
    icon: '⚡',
    difficulty: 2,
    audience: '容易冲动误点 · 反应快但错误率偏高者',
    prescription: '练习 2 组，培养“三思而后点”的定力',
    brainTarget: '前额叶背外侧皮质的反应抑制机制（Go/No-Go 范式）',
    desc: '全盘包含 1-16，但只允许按序寻找奇数，偶数方格全为干扰项，极度考验自制力。',
    targetDuration: '目标: 4×4 奇数零失误 < 10 秒',
    config: { size: 4, shape: 'grid', mode: 'numbers_odd', centerFocusDot: false },
    stages: [
      { step: 1, name: '奇数规则确立', detail: '脑中时刻默念 1, 3, 5, 7, 9... 序列' },
      { step: 2, name: '压制偶数冲动', detail: '余光看到 2, 4 等偶数时强力克制触按冲动' },
      { step: 3, name: '纯粹奇数连贯', detail: '保持零失误完成所有奇数点击' },
    ],
  },
  {
    id: 'plan-020',
    level: 20,
    category: 'executive',
    title: '4×4 偶数专注抑制筛选',
    subtitle: '仅点击偶数 2,4,6.. · 奇数充当强干扰项',
    tag: '偶数抑制',
    tagColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    icon: '🛡️',
    difficulty: 2,
    audience: '需训练严苛规则执行力 · 消除粗心毛躁者',
    prescription: '每日 2 组，体验规则倒转下的抑制控制',
    brainTarget: '抑制控制神经回路与工作记忆线索刷新',
    desc: '与奇数筛选相反，本方案只准寻找偶数，奇数全为诱饵，考察思维定势的迅速翻转。',
    targetDuration: '目标: 4×4 偶数零失误 < 10 秒',
    config: { size: 4, shape: 'grid', mode: 'numbers_even', centerFocusDot: false },
    stages: [
      { step: 1, name: '双数规则起步', detail: '从 2 沉着开始，视线主动锁定双数特征' },
      { step: 2, name: '排除奇数诱惑', detail: '余光扫描时主动略过 1, 3, 5 等奇数' },
      { step: 3, name: '精准完赛', detail: '连贯找齐 2, 4, 6... 16' },
    ],
  },
  {
    id: 'plan-021',
    level: 21,
    category: 'executive',
    title: '4×4 步长跳跃跨度思维',
    subtitle: '+2 递增跳跃跨步 · 结合瞬时心算与搜视',
    tag: '步长跨步',
    tagColor: 'bg-amber-100 text-amber-800 border-amber-300',
    icon: '🦘',
    difficulty: 3,
    audience: '习惯按 +1 机械查找 · 需加强脑力工作记忆刷新者',
    prescription: '晨读前练习 2 组，激活短时记忆缓冲栈',
    brainTarget: '心算结果与视觉目标匹配的并行处理通路',
    desc: '以 +2 为步长连续跨越查找（1, 3, 5, 7, 9...），打破连续自然数预判惯性。',
    targetDuration: '目标: 4×4 跨步 < 14 秒',
    config: { size: 4, shape: 'grid', mode: 'numbers_skip', centerFocusDot: false },
    stages: [
      { step: 1, name: '步长心理预载', detail: '点中当前数时，提前在脑中算好下个数' },
      { step: 2, name: '数值视觉转化', detail: '将算出的目标值迅速转化为视觉图像搜查' },
      { step: 3, name: '匀速跨步连击', detail: '全程不卡顿，如节拍器般匀速命中' },
    ],
  },
  {
    id: 'plan-022',
    level: 22,
    category: 'executive',
    title: '4×4 罗马数字视觉转码',
    subtitle: '古罗马数码 I, II, III.. · 激活跨符号转译中枢',
    tag: '符号转码',
    tagColor: 'bg-yellow-100 text-yellow-800 border-yellow-300',
    icon: '🏛️',
    difficulty: 3,
    audience: '希望提升跨模态抽象符号处理速度的学生与脑力从业者',
    prescription: '练习 2 组，强化对 I, V, X, L 组合构成的瞬间反应',
    brainTarget: '左脑角回及枕颞区视觉词形区（VWFA）的字符转码',
    desc: '按正序寻找罗马数字 I 至 XVI，锻炼大脑在阿拉伯数字意图与罗马字符视觉间的实时解码。',
    targetDuration: '目标: 4×4 罗马字 < 15 秒',
    config: { size: 4, shape: 'grid', mode: 'roman_numerals', centerFocusDot: false },
    stages: [
      { step: 1, name: '基础罗马符激活', detail: '熟悉 I, II, III, IV, V, VI 等字形特征' },
      { step: 2, name: '转码提前量', detail: '脑中想 7 时，视野直接去抓 VII' },
      { step: 3, name: '跨越整十位', detail: '顺利过渡 IX, X, XI, XII 至 XVI' },
    ],
  },
  {
    id: 'plan-023',
    level: 23,
    category: 'executive',
    title: '4×4 经典心理学红黑双轨方格',
    subtitle: '红黑双色 · 双序列规则性抑制',
    tag: '经典心理学',
    tagColor: 'bg-rose-100 text-rose-800 border-rose-300',
    icon: '🔴',
    difficulty: 3,
    audience: '注意力容易涣散 · 需要强化神经意志力与抑制无关诱惑者',
    prescription: '练习 2 组，保持高度平心静气与专注辨识',
    brainTarget: '红奇数与黑偶数/红黑交替，抑制强烈的单一颜色直觉反应',
    desc: '源自经典心理学注意力分配测试，要求在红黑两色数字中按双轨特定规则搜寻点击。',
    targetDuration: '目标: 4×4 红黑 < 16 秒',
    config: { size: 4, shape: 'grid', mode: 'red_black', centerFocusDot: false },
    stages: [
      { step: 1, name: '颜色与数值解绑', detail: '清晰辨认当前应找的是红色还是黑色' },
      { step: 2, name: '抑制诱惑冲动', detail: '余光看到相近数值但颜色不对时迅速过滤' },
      { step: 3, name: '双轨平稳推进', detail: '全程维持零失误，养成沉稳决断的定力' },
    ],
  },
  {
    id: 'plan-024',
    level: 24,
    category: 'executive',
    title: '4×4 奇偶双轨交替转换',
    subtitle: '奇数与偶数交叉寻索 · 双规则敏捷换轨',
    tag: '奇偶交替',
    tagColor: 'bg-sky-100 text-sky-800 border-sky-300',
    icon: '🔀',
    difficulty: 3,
    audience: '思维惯性强 · 处理不同任务时容易思维打结的人群',
    prescription: '工作前练习 2 组，活化额叶执行控制灵活性',
    brainTarget: '认知灵活性（Cognitive Flexibility）与规则集合切换',
    desc: '奇1 ➔ 偶2 ➔ 奇3 ➔ 偶4... 大脑必须连续交替判断奇偶性与大小，防止思维惰性。',
    targetDuration: '目标: 4×4 奇偶交替 < 16 秒',
    config: { size: 4, shape: 'grid', mode: 'odd_even_switch', centerFocusDot: false },
    stages: [
      { step: 1, name: '规则交替预演', detail: '脑海中保持“奇-偶-奇-偶”的节拍提示' },
      { step: 2, name: '瞬时属性核验', detail: '点击前瞬间确认当前目标的奇偶属性' },
      { step: 3, name: '无缝连续点击', detail: '消除换轨时的迟滞感，行云流水通关' },
    ],
  },
  {
    id: 'plan-025',
    level: 25,
    category: 'executive',
    title: '4×4 数字字母双轨连线 Trail Making',
    subtitle: '连线测验经典范式 · 1-A-2-B 规则切换',
    tag: '双轨交替',
    tagColor: 'bg-blue-100 text-blue-800 border-blue-300',
    icon: '🔀',
    difficulty: 4,
    audience: '多任务频繁切换人群 · 感觉思维容易卡壳与分心者',
    prescription: '工作或深度学习前练习 2 组，调动额叶执行控制力',
    brainTarget: '工作记忆中同时保持数字与字母两条线索，频繁无缝切换规则',
    desc: '按 1-A-2-B-3-C... 交替检索，国际神经心理学标准 Trail Making Test 经典测试。',
    targetDuration: '目标: 4×4 双轨 < 18 秒',
    config: { size: 4, shape: 'grid', mode: 'trail_making', centerFocusDot: false },
    stages: [
      { step: 1, name: '双线索记忆保持', detail: '点击当前数字时，大脑提前预载下一个目标字母' },
      { step: 2, name: '敏捷规则切换', detail: '每点击一次立即切换思维范畴，避免思维惰性' },
      { step: 3, name: '平稳节奏推进', detail: '在数字与英文字母间保持准确率与高节奏' },
    ],
  },
  {
    id: 'plan-026',
    level: 26,
    category: 'executive',
    title: '5×5 逆向倒序思维强化方案',
    subtitle: '25→1 逆序倒数 · 抑制顺行冲动',
    tag: '逆向倒序',
    tagColor: 'bg-amber-100 text-amber-800 border-amber-300',
    icon: '⏳',
    difficulty: 4,
    audience: '习惯顺行思维定势 · 欲锻炼反向推导与逻辑灵活度者',
    prescription: '每日 1-2 组，强迫大脑跳出常规自动驾驶模式',
    brainTarget: '倒序认知加工，反向检索，阻断习惯性顺行神经回路',
    desc: '从 25 递减点击至 1。因为日常大脑对正序极度熟悉，倒序能深度激活前额叶控制。',
    targetDuration: '目标: 5×5 逆序 < 28 秒',
    config: { size: 5, shape: 'grid', mode: 'numbers_desc', centerFocusDot: false },
    stages: [
      { step: 1, name: '重置数字倒退', detail: '每一步都需在脑中倒退递减，打破直觉正数冲动' },
      { step: 2, name: '预判倒数步调', detail: '找到 20 时，视线顺势预判 19、18 的所在方位' },
      { step: 3, name: '冲刺收尾定力', detail: '倒数至最后 5 个数字时克服松懈心理，极速收官' },
    ],
  },
  {
    id: 'plan-027',
    level: 27,
    category: 'executive',
    title: '5×5 菱形斜角思维转移',
    subtitle: '菱形斜角排布 + 逆向思维 · 空间与逻辑双重转换',
    tag: '空间转换',
    tagColor: 'bg-cyan-100 text-cyan-800 border-cyan-300',
    icon: '💠',
    difficulty: 4,
    audience: '长时间处理单调数据 · 思维容易固化僵滞的专业人士',
    prescription: '午间放松或会议前练习 1 组，快速激活大脑空间灵活性',
    brainTarget: '强制大脑在 45 度斜向轴上建立新型空间坐标映射，拓展神经突触连接',
    desc: '将方格旋转 45 度形成菱形阵列，消除水平阅读偏向，重组空间搜索逻辑。',
    targetDuration: '目标: 5×5 菱形逆序 < 32 秒',
    config: { size: 5, shape: 'diamond', mode: 'numbers_desc', centerFocusDot: true },
    stages: [
      { step: 1, name: '重塑对角基准', detail: '适应斜向的主对角线与副对角线结构' },
      { step: 2, name: '四个锐角边际搜查', detail: '快速排查上下左右四个顶点的边缘数字' },
      { step: 3, name: '中心扩散连击', detail: '由中心向外围斜向扩散，维持连贯节奏' },
    ],
  },
  {
    id: 'plan-028',
    level: 28,
    category: 'executive',
    title: '5×5 格尔波夫宇航员红升黑降',
    subtitle: '经典 Gorbov Table · 红升黑降双轨交替',
    tag: '宇航员核心',
    tagColor: 'bg-rose-100 text-rose-800 border-rose-300',
    icon: '🚀',
    difficulty: 5,
    audience: '高压多任务职业 · 飞行员与宇航员心理学标准测试 · 极限抗干扰者',
    prescription: '建议每周练习 3 次，感受红升黑降双向思维的极限拉扯与稳定性',
    brainTarget: '双轨工作记忆同时保持红升与黑降，极度考验注意力分配与心智耐受力',
    desc: '红升黑降交替搜索：红1 ➔ 黑12 ➔ 红2 ➔ 黑11 ➔ 红3 ➔ 黑10... 心理学殿堂级注意力分配测试。',
    targetDuration: '目标: 5×5 格尔波夫 < 35 秒',
    config: { size: 5, shape: 'grid', mode: 'red_asc_black_desc', centerFocusDot: false },
    stages: [
      { step: 1, name: '双通道记忆并存', detail: '红序列正向递增，黑序列逆向递减，大脑需同时记录两组数字' },
      { step: 2, name: '极速思维换轨', detail: '每点中一个立即换轨切换颜色与方向，绝不允许思维惯性' },
      { step: 3, name: '中途抗疲劳维持', detail: '在训练中段（两组数字相遇附近）保持高定力，杜绝混淆' },
    ],
  },
  {
    id: 'plan-029',
    level: 29,
    category: 'executive',
    title: '5×5 蜂巢错位 Trail Making 双轨连线',
    subtitle: '蜂窝六边形 + 1-A-2-B 双轨连线',
    tag: '蜂窝双轨',
    tagColor: 'bg-purple-100 text-purple-800 border-purple-300',
    icon: '🐝',
    difficulty: 4,
    audience: '需应对复杂非线性任务的高级项目主管与架构师',
    prescription: '攻克复杂工作前练习 1 组，体验非线性拓扑下的清晰条理',
    brainTarget: '非正交网格几何与抽象符号双轨切换的联合计算',
    desc: '在非正交的六边形蜂窝节点中，执行 1-A-2-B 数字与字母交替，双重打破思维定式。',
    targetDuration: '目标: 5×5 蜂巢双轨 < 32 秒',
    config: { size: 5, shape: 'honeycomb', mode: 'trail_making', centerFocusDot: false },
    stages: [
      { step: 1, name: '蜂窝节点寻径', detail: '视线在六边形交错间自如穿梭' },
      { step: 2, name: '数字字母无隙衔接', detail: '不被相邻非目标符号带偏' },
      { step: 3, name: '保持条理通关', detail: '全程保持清晰的脑内双线追踪' },
    ],
  },
  {
    id: 'plan-030',
    level: 30,
    category: 'executive',
    title: '5×5 奇数筛选大盘高压测试',
    subtitle: '25 格全盘排查 · 仅点选奇数 1..25',
    tag: '大盘奇数',
    tagColor: 'bg-blue-100 text-blue-800 border-blue-300',
    icon: '⚡',
    difficulty: 4,
    audience: '需要提升高强度审查准确率的财务、风控与代码审计人员',
    prescription: '进行核对工作前练习 2 组，将大脑微细筛选力调至峰值',
    brainTarget: '长序列抑制控制与模式过滤网络的高效运作',
    desc: '面对 25 个密集分布的数字，精准找出 1, 3, 5... 25 并坚决不点偶数，要求 100% 准确度。',
    targetDuration: '目标: 5×5 奇数零失误 < 18 秒',
    config: { size: 5, shape: 'grid', mode: 'numbers_odd', centerFocusDot: false },
    stages: [
      { step: 1, name: '大盘基调建立', detail: '从 1 开始建立稳扎稳打的奇数基调' },
      { step: 2, name: '强力抑制中间偶数', detail: '遇到偶数诱饵坚决不碰' },
      { step: 3, name: '25 零失误完美收尾', detail: '以严谨准确率完成全部奇数搜寻' },
    ],
  },
  {
    id: 'plan-031',
    level: 31,
    category: 'executive',
    title: '5×5 偶数筛选大盘抗诱惑方案',
    subtitle: '25 格全盘排查 · 仅点选偶数 2..24',
    tag: '大盘偶数',
    tagColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    icon: '🛡️',
    difficulty: 4,
    audience: '容易被无关诱惑分心 · 需强化抵抗冲动意志力者',
    prescription: '每日 1-2 组，培养强大的抗干扰心理防火墙',
    brainTarget: '前额叶眶额区对冲动行为的即时刹车控制',
    desc: '与奇数筛选形成互补，全神贯注检索偶数，在错综复杂的数字丛林中保持绝对冷峻。',
    targetDuration: '目标: 5×5 偶数零失误 < 18 秒',
    config: { size: 5, shape: 'grid', mode: 'numbers_even', centerFocusDot: false },
    stages: [
      { step: 1, name: '锁定偶数基频', detail: '由 2 起步，形成偶数心理节奏' },
      { step: 2, name: '过滤密集奇数', detail: '奇数出现时视线瞬间滑过不点击' },
      { step: 3, name: '至 24 达成全胜', detail: '全过程保持零失误零罚时' },
    ],
  },
  {
    id: 'plan-032',
    level: 32,
    category: 'executive',
    title: '5×5 步长跳跃大跨度推演',
    subtitle: '+2 跨步跳跃寻数至 49 · 强化连续心算与视觉搜寻',
    tag: '高阶跨步',
    tagColor: 'bg-amber-100 text-amber-800 border-amber-300',
    icon: '🦘',
    difficulty: 4,
    audience: '需经常处理数字与逻辑推导的理科生与分析师',
    prescription: '练习 2 组，感受心算数值与视野卡块的无缝共振',
    brainTarget: '顶内沟（IPS）数字加工与额极区（FPI）规划控制的协同',
    desc: '从 1 连续跨步递增 (+2) 至 49，不仅考验视野，更考验大脑连续推演的流畅度。',
    targetDuration: '目标: 5×5 步长跳跃 < 26 秒',
    config: { size: 5, shape: 'grid', mode: 'numbers_skip', centerFocusDot: false },
    stages: [
      { step: 1, name: '个位跨步平顺', detail: '1, 3, 5, 7, 9 极速完成' },
      { step: 2, name: '十位数跳跃无阻', detail: '进入 11-39 保持推导清晰' },
      { step: 3, name: '49 极限撞线', detail: '顺利点中最后一个跨步目标' },
    ],
  },
  {
    id: 'plan-033',
    level: 33,
    category: 'executive',
    title: '5×5 罗马数字大盘转码挑战',
    subtitle: 'I 至 XXV 罗马数字 · 全盘快速跨语系转译',
    tag: '大盘罗马',
    tagColor: 'bg-yellow-100 text-yellow-800 border-yellow-300',
    icon: '🏛️',
    difficulty: 4,
    audience: '需强化跨文化符号理解与图形转码能力的学者与翻译人员',
    prescription: '每周练习 2-3 次，建立罗马数码直觉识别表象',
    brainTarget: '双侧枕颞联合区对复合异构字符的瞬时特征抽取',
    desc: '由 I 搜至 XXV，包括 IV, IX, XIV, XIX, XXIV 等复杂组合，考验快速符号转译。',
    targetDuration: '目标: 5×5 罗马大盘 < 30 秒',
    config: { size: 5, shape: 'grid', mode: 'roman_numerals', centerFocusDot: false },
    stages: [
      { step: 1, name: '单位数罗马字速击', detail: 'I 至 X 快速铺垫' },
      { step: 2, name: '十位数复合转码', detail: '熟练提取 XI 至 XX 各项' },
      { step: 3, name: 'XXV 完美收官', detail: '最后 5 个复合字符沉着定位' },
    ],
  },
  {
    id: 'plan-034',
    level: 34,
    category: 'executive',
    title: '6×6 逆向倒序大纵深长跑',
    subtitle: '36 格全盘倒数 36→1 · 逆向逻辑高强度持续运算',
    tag: '长效逆思',
    tagColor: 'bg-amber-100 text-amber-900 border-amber-300',
    icon: '🛡️',
    difficulty: 5,
    audience: '习惯思维浅层化 · 欲锻炼长时间深度专注思考的脑力工作者',
    prescription: '完成大型烧脑工作前作为思维预热，体验高负荷认知心流',
    brainTarget: '长达数十步的持续反向逻辑推演，全面锻炼思维耐受力',
    desc: '36 格逆向倒序，连续在脑中完成 36 次逆推与大盘面定位，极具挑战性。',
    targetDuration: '目标: 6×6 逆序 < 55 秒',
    config: { size: 6, shape: 'grid', mode: 'numbers_desc', centerFocusDot: false },
    stages: [
      { step: 1, name: '大盘面逆向启动', detail: '从 36 沉着起步，构建逆向倒数的心理节拍' },
      { step: 2, name: '跨十位转换平顺', detail: '在 30、20、10 跨整十位时平稳衔接' },
      { step: 3, name: '最后十格极速收盘', detail: '进入个位数后全面释放余光，快速锁定通关' },
    ],
  },
  {
    id: 'plan-035',
    level: 35,
    category: 'executive',
    title: '6×6 心理学红黑双轨大盘',
    subtitle: '36 格红黑双色 · 双向思维高压拉伸',
    tag: '红黑大盘',
    tagColor: 'bg-rose-100 text-rose-800 border-rose-300',
    icon: '🔴',
    difficulty: 5,
    audience: '高难度认知训练者 · 飞行器操控与紧急指挥人员',
    prescription: '精力充沛时练习 1 组，体验高密度双轨规则下的心如止水',
    brainTarget: '前额叶背外侧区高负荷信息切换与多通道分配',
    desc: '在 36 个红黑格中按序交替检索，双轨信息容量大幅扩增，不容丝毫杂念。',
    targetDuration: '目标: 6×6 红黑 < 50 秒',
    config: { size: 6, shape: 'grid', mode: 'red_black', centerFocusDot: false },
    stages: [
      { step: 1, name: '前 12 步基线建立', detail: '稳住红黑交替韵律' },
      { step: 2, name: '中段 12 步抗疲劳', detail: '克服双轨交织带来的视觉疲惫' },
      { step: 3, name: '后段 12 步精准冲刺', detail: '零失误完成全部双轨对应' },
    ],
  },
  {
    id: 'plan-036',
    level: 36,
    category: 'executive',
    title: '6×6 格尔波夫超限红升黑降',
    subtitle: '红1至18升，黑18至1降 · 殿堂级双向思维熔炉',
    tag: '超限双轨',
    tagColor: 'bg-rose-900 text-amber-200 border-rose-700',
    icon: '🚀',
    difficulty: 5,
    audience: '宇航员选拔标准挑战者 · 追求心智极致自控力的高级认知学者',
    prescription: '每周挑战 1 次，见证在极度复杂交织规则下的冷静超然',
    brainTarget: '工作记忆极限维持、注意广度与多任务仲裁机制的巅峰考验',
    desc: '红1-黑18-红2-黑17-红3-黑16... 36步红升黑降交替，航天心理学最高标准测试之一。',
    targetDuration: '目标: 6×6 格尔波夫 < 55 秒',
    config: { size: 6, shape: 'grid', mode: 'red_asc_black_desc', centerFocusDot: false },
    stages: [
      { step: 1, name: '双向起势', detail: '红升与黑降各就各位' },
      { step: 2, name: '两向汇合点决断', detail: '在红黑数值在中间相遇时杜绝混淆' },
      { step: 3, name: '分道扬镳收盘', detail: '两组数字背向拉开距离直至全部命中' },
    ],
  },

  // =========================================================================
  // 3. 国风速读与语言编码学院 (L37 - L54)
  // =========================================================================
  {
    id: 'plan-037',
    level: 37,
    category: 'reading',
    title: '4×4 汉语拼音声母启蒙搜视',
    subtitle: 'b, p, m, f.. 声母表顺序 · 视听读语言整合',
    tag: '拼音声母',
    tagColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    icon: '🔤',
    difficulty: 2,
    audience: '青少年语言学习 · 拼音打字工作者 · 语言康复训练',
    prescription: '每日 2 组，边默读发音边快速定位',
    brainTarget: '布罗卡区（Broca）语音编码与视皮层字符识别协同',
    desc: '按汉语拼音声母自然顺序依次寻找，将听觉语音感知与视觉搜寻紧密咬合。',
    targetDuration: '目标: 4×4 拼音 < 12 秒',
    config: { size: 4, shape: 'grid', mode: 'chinese_pinyin', centerFocusDot: false },
    stages: [
      { step: 1, name: '唇音舌音连发', detail: 'b, p, m, f 快速击发' },
      { step: 2, name: '舌尖音平顺', detail: 'd, t, n, l 自然承接' },
      { step: 3, name: '舌根音收束', detail: 'g, k, h, j 顺畅通关' },
    ],
  },
  {
    id: 'plan-038',
    level: 38,
    category: 'reading',
    title: '4×4 天干地支国风心流方案',
    subtitle: '甲乙丙丁子丑寅卯 · 传统序列时序检索',
    tag: '国风时序',
    tagColor: 'bg-teal-100 text-teal-800 border-teal-300',
    icon: '📜',
    difficulty: 3,
    audience: '喜爱传统国风文化 · 锻炼时序知识与空间定位双重记忆',
    prescription: '练习 2 组，既重温天干地支顺序，又锻炼敏捷视野搜寻',
    brainTarget: '文化符号编码抽取与瞬时视野定位协同',
    desc: '甲乙丙丁至子丑寅卯，古老干支符号与现代舒尔特测验结合，沉淀心神。',
    targetDuration: '目标: 4×4 天干地支 < 14 秒',
    config: { size: 4, shape: 'grid', mode: 'chinese_stems', centerFocusDot: false },
    stages: [
      { step: 1, name: '干支序列唤醒', detail: '顺应天干与地支自然序列，大脑快速提取知识点' },
      { step: 2, name: '汉字结构速判', detail: '在方块字特定字形结构中快速定位当前目标字' },
      { step: 3, name: '沉浸国风意境', detail: '静心专注，感受传统历法符号背后的从容与律动' },
    ],
  },
  {
    id: 'plan-039',
    level: 39,
    category: 'reading',
    title: '4×4 经典成语连环接力',
    subtitle: '四字成语字序逐字接力 · 寓教于乐',
    tag: '成语接力',
    tagColor: 'bg-amber-100 text-amber-800 border-amber-300',
    icon: '🏮',
    difficulty: 2,
    audience: '学生语文积累 · 中文母语者 · 休闲益智人群',
    prescription: '每日 2 组，体会成语字序流转中的自然语义指引',
    brainTarget: '语义记忆与瞬时字形扫描的联合检索',
    desc: '涵盖经典四字成语，顺着词语语义语流逐字寻找，生动有趣且加深词汇记忆。',
    targetDuration: '目标: 4×4 成语 < 13 秒',
    config: { size: 4, shape: 'grid', mode: 'chinese_idioms', centerFocusDot: false },
    stages: [
      { step: 1, name: '成语词头起步', detail: '根据词首快速锁定成语' },
      { step: 2, name: '四字顺次完成', detail: '逐字寻找构成完整成语' },
      { step: 3, name: '接力下一成语', detail: '无缝进入下一个四字成语' },
    ],
  },
  {
    id: 'plan-040',
    level: 40,
    category: 'reading',
    title: '4×4 英文大写字母正序敏锐搜视',
    subtitle: 'A 至 P 字母序列 · 跨语言字符快速扫描',
    tag: '字母正序',
    tagColor: 'bg-blue-100 text-blue-800 border-blue-300',
    icon: '🔤',
    difficulty: 2,
    audience: '英语学习者 · 需快速查阅外文文献或编程代码的技术人员',
    prescription: '每日 2 组，强化对英文英文字母形态特征的敏感度',
    brainTarget: '左脑语言区视觉字形加工中枢的高频连续刺激',
    desc: '按 A、B、C... 至 P 的英文字母次序连续排查，锻炼外文字符的快速识别与眼动定位。',
    targetDuration: '目标: 4×4 字母 < 11 秒',
    config: { size: 4, shape: 'grid', mode: 'letters_asc', centerFocusDot: false },
    stages: [
      { step: 1, name: '字母自然联想', detail: '脑海自然流淌字母歌节拍，提前预载下一字符' },
      { step: 2, name: '外文形态速辨', detail: '快速分辨易混淆字形（如 E/F, C/G）' },
      { step: 3, name: '一气呵成点击', detail: '保持稳定手指触控，行云流水完成' },
    ],
  },
  {
    id: 'plan-041',
    level: 41,
    category: 'reading',
    title: '4×4 英文字母逆向倒序',
    subtitle: 'P 倒数至 A · 反转语言自动加工习惯',
    tag: '字母逆序',
    tagColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    icon: '🔤',
    difficulty: 3,
    audience: '英语专业学生 · 程序员 · 欲突破习惯性语言定势者',
    prescription: '每周练习 3 次，感受字母逆排对脑力的深度刺激',
    brainTarget: '打破熟练语言脚本的自动执行，强迫前额叶主动干预介入',
    desc: '从 P 逆向倒数寻找至 A，克服日常正序习惯，强力锻炼大脑语言工作记忆检索。',
    targetDuration: '目标: 4×4 字母倒序 < 14 秒',
    config: { size: 4, shape: 'grid', mode: 'letters_desc', centerFocusDot: false },
    stages: [
      { step: 1, name: '反向字母表检索', detail: '脑海迅速倒推前置字母' },
      { step: 2, name: '视觉定位目标', detail: '在方块中快速锁定目标字符' },
      { step: 3, name: '至 A 极速冲线', detail: '最后字母行云流水完成' },
    ],
  },
  {
    id: 'plan-042',
    level: 42,
    category: 'reading',
    title: '4×4 字母大小写双轨交替',
    subtitle: 'A ➔ a ➔ B ➔ b.. · 微细字形笔画瞬时辨识',
    tag: '大小写交替',
    tagColor: 'bg-purple-100 text-purple-800 border-purple-300',
    icon: '🔤',
    difficulty: 3,
    audience: '对外文字形细节敏感度低 · 容易忽略大小写区别的人群',
    prescription: '练习 2 组，锻炼眼睛对大小写形态特征的精细解构',
    brainTarget: '高级视觉皮层对同义不同形（Allograph）字符的认知归纳与分离',
    desc: '大写 A ➔ 小写 a ➔ 大写 B ➔ 小写 b... 在相同语义但不同视觉字形间快速穿梭。',
    targetDuration: '目标: 4×4 大小写 < 14 秒',
    config: { size: 4, shape: 'grid', mode: 'letters_case', centerFocusDot: false },
    stages: [
      { step: 1, name: '大写起手，小写跟进', detail: '牢固把握“一大一小”交替节拍' },
      { step: 2, name: '辨析同异形', detail: '区分如 C/c, O/o 仅靠尺寸大小分辨的字形' },
      { step: 3, name: '连贯通关', detail: '无缝保持高精细度点击' },
    ],
  },
  {
    id: 'plan-043',
    level: 43,
    category: 'reading',
    title: '5×5 千字文汉字速读识别',
    subtitle: '天地玄黄宇宙洪荒 · 整体字形瞬间摄入',
    tag: '文字速读',
    tagColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    icon: '📖',
    difficulty: 4,
    audience: '阅读速度慢 · 习惯逐字默读发音 · 考研与备考学生',
    prescription: '阅读或工作前练习 1-2 组，快速进入高效阅读吸收态',
    brainTarget: '汉字整体字形感知，跳过内语音发声（声带默念），拓展字词感知宽度',
    desc: '利用千字文自然语感，练习将汉字作为图形整体快速摄入与定位，提高阅读效率。',
    targetDuration: '目标: 5×5 千字文 < 28 秒',
    config: { size: 5, shape: 'grid', mode: 'chinese_chars', centerFocusDot: false },
    stages: [
      { step: 1, name: '图形化整体识别', detail: '将汉字作为整体图形识别，跳过心中的默读发音' },
      { step: 2, name: '拓宽字词扫视', detail: '扩大单次注视所能涵盖的汉字数量与周边辨识度' },
      { step: 3, name: '韵文语感连贯', detail: '按天地玄黄宇宙洪荒次序，形成极具美感的心流' },
    ],
  },
  {
    id: 'plan-044',
    level: 44,
    category: 'reading',
    title: '5×5 传世唐诗绝句韵律专注',
    subtitle: '李白孟浩然传世绝句 · 诗意与视觉深度共鸣',
    tag: '诗词国风',
    tagColor: 'bg-amber-100 text-amber-800 border-amber-300',
    icon: '🏮',
    difficulty: 3,
    audience: '学生背诗启蒙 · 喜爱中华古诗词 · 寻求美感与专注共鸣的人群',
    prescription: '晨读或睡前练习 2 组，将诗歌韵律与视觉搜寻完美融为一体',
    brainTarget: '诗词语言序列与大范围汉字空间定位深度整合，激活语言情境神经元',
    desc: '收录《静夜思》《登鹳雀楼》《春晓》等名篇，按绝句行句逐字寻索，富有深厚文化意境。',
    targetDuration: '目标: 5×5 古诗词 < 26 秒',
    config: { size: 5, shape: 'grid', mode: 'chinese_poetry', centerFocusDot: false },
    stages: [
      { step: 1, name: '诗意意象共鸣', detail: '在脑海中浮现诗句情境，顺着韵律自然流转' },
      { step: 2, name: '跨行连贯字索', detail: '行句更替时视线无缝承接，形成行云流水的搜寻感' },
      { step: 3, name: '全篇诗境通达', detail: '点完最后一个字时，全篇诗词在胸中浑然一体' },
    ],
  },
  {
    id: 'plan-045',
    level: 45,
    category: 'reading',
    title: '5×5 天干地支全域大盘',
    subtitle: '甲乙丙丁至子丑寅卯 · 全序列时序知识大排查',
    tag: '干支大盘',
    tagColor: 'bg-teal-100 text-teal-800 border-teal-300',
    icon: '📜',
    difficulty: 3,
    audience: '国学爱好者 · 传统历法学习者 · 需锻炼大盘字形定位者',
    prescription: '每日 1 组，温故而知新，沉静自心',
    brainTarget: '传统序列知识脑内长期记忆与即时视觉匹配映射',
    desc: '天干十干加地支十二支，在大盘面上展开系统检索，体味中国传统计时符号的雅致。',
    targetDuration: '目标: 5×5 天干地支 < 26 秒',
    config: { size: 5, shape: 'grid', mode: 'chinese_stems', centerFocusDot: false },
    stages: [
      { step: 1, name: '天干十干先行', detail: '甲乙丙丁戊己庚辛壬癸' },
      { step: 2, name: '地支十二支接力', detail: '子丑寅卯辰巳午未申酉戌亥' },
      { step: 3, name: '全盘贯通', detail: '一气呵成完成全套干支检索' },
    ],
  },
  {
    id: 'plan-046',
    level: 46,
    category: 'reading',
    title: '5×5 经典成语长链寻踪',
    subtitle: '四字成语多组接力 · 强化成语熟练度与词形扫视',
    tag: '成语长链',
    tagColor: 'bg-amber-100 text-amber-800 border-amber-300',
    icon: '🏮',
    difficulty: 3,
    audience: '希望提升文字摄入敏感度与词汇调用能力的学生与文职人员',
    prescription: '写作或备考前练习 2 组，快速激活词汇大脑网络',
    brainTarget: '词汇语境关联网络与视觉字符位置映射',
    desc: '包含多组高频成语，按字序依次接力寻找，边练专注边积累词汇。',
    targetDuration: '目标: 5×5 成语长链 < 27 秒',
    config: { size: 5, shape: 'grid', mode: 'chinese_idioms', centerFocusDot: false },
    stages: [
      { step: 1, name: '首字识别抓取', detail: '看到首字迅速脑补全词' },
      { step: 2, name: '后三字顺风追索', detail: '视线如飞箭锁定后续三个字' },
      { step: 3, name: '词群交替收盘', detail: '在多个成语间自如切换' },
    ],
  },
  {
    id: 'plan-047',
    level: 47,
    category: 'reading',
    title: '5×5 26 英文字母全景搜视',
    subtitle: 'A-Z 全字母正序检索 · 英语词根阅读基础',
    tag: '26字母全景',
    tagColor: 'bg-blue-100 text-blue-800 border-blue-300',
    icon: '🔤',
    difficulty: 3,
    audience: '英语学习者 · 出国留学备考者 · 程序员代码检索提速',
    prescription: '每日 2 组，培养对全套字母特征的秒速辨别',
    brainTarget: '左脑字母识别区与手眼协调皮层的高效联动',
    desc: '按 A、B、C... 至 Y/Z 的英文字母次序连续排查，锻炼外文字符的快速识别与眼动定位。',
    targetDuration: '目标: 5×5 字母全景 < 25 秒',
    config: { size: 5, shape: 'grid', mode: 'letters_asc', centerFocusDot: false },
    stages: [
      { step: 1, name: 'A-G 极速起步', detail: '自然唱诵字母歌旋律起步' },
      { step: 2, name: 'H-S 中段稳进', detail: '克服中间字符干扰，平稳推进' },
      { step: 3, name: 'T-Z 冲刺撞线', detail: '最后阶段一气呵成完成' },
    ],
  },
  {
    id: 'plan-048',
    level: 48,
    category: 'reading',
    title: '5×5 26 字母逆向倒序飞跃',
    subtitle: 'Z 倒数至 A · 全字母逆向脑力挑战',
    tag: '全字母倒序',
    tagColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    icon: '🔤',
    difficulty: 4,
    audience: '英语高阶学者 · 极速键盘盲打者 · 需提升非常规抗逆思维者',
    prescription: '每周练习 2 次，体验不按常规出牌的神经深度拉伸',
    brainTarget: '语言记忆反向推演，强化左半球额叶执行网络激活',
    desc: '从 Z 开始倒数逆序查找至 A，在 25 格复杂盘面里完成反向语言检索。',
    targetDuration: '目标: 5×5 字母倒序 < 28 秒',
    config: { size: 5, shape: 'grid', mode: 'letters_desc', centerFocusDot: false },
    stages: [
      { step: 1, name: 'Z-T 逆向起步', detail: '从 Z 倒推检索，建立反向心理表象' },
      { step: 2, name: 'S-H 中段攻坚', detail: '在脑中迅速倒排前序字母并抓取' },
      { step: 3, name: 'G-A 极速收官', detail: '最终冲回起点 A，完成反向闭环' },
    ],
  },
  {
    id: 'plan-049',
    level: 49,
    category: 'reading',
    title: '5×5 全字母大小写交替流转',
    subtitle: 'A ➔ a ➔ B ➔ b.. · 50个字形维度的精细辨别',
    tag: '全盘大小写',
    tagColor: 'bg-purple-100 text-purple-800 border-purple-300',
    icon: '🔤',
    difficulty: 4,
    audience: 'UI/UX 设计师 · 英文校对人员 · 需训练精细眼力者',
    prescription: '练习 2 组，锻炼眼睛在瞬间识别微细笔画差别',
    brainTarget: '高阶视皮层腹侧流通路对字符微结构的精细调制',
    desc: '在大盘面上同时呈现大写与小写，必须严格按 A-a-B-b 交替辨别，眼光敏锐度极佳训练。',
    targetDuration: '目标: 5×5 大小写 < 28 秒',
    config: { size: 5, shape: 'grid', mode: 'letters_case', centerFocusDot: false },
    stages: [
      { step: 1, name: '大写起手，小写紧随', detail: '保持每步变换形态的注意警觉' },
      { step: 2, name: '规避笔画陷阱', detail: '快速分辨同形大小字符' },
      { step: 3, name: '节奏如流水', detail: '连贯无阻完成 25 步交替' },
    ],
  },
  {
    id: 'plan-050',
    level: 50,
    category: 'reading',
    title: '5×5 汉语拼音全声母大盘',
    subtitle: 'b, p, m, f 至 y, w 全声母体系化巩固',
    tag: '全拼音声母',
    tagColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    icon: '🔤',
    difficulty: 3,
    audience: '语文教师 · 学生 · 普通话语音训练者',
    prescription: '每日 1-2 组，巩固标准声母表发音与字形联结',
    brainTarget: '汉语言音位编码与视觉符号的空间一体化映射',
    desc: '从唇音到舌尖中音、舌根音、舌面音、平翘舌音，完整梳理声母表，寓教于练。',
    targetDuration: '目标: 5×5 拼音大盘 < 25 秒',
    config: { size: 5, shape: 'grid', mode: 'chinese_pinyin', centerFocusDot: false },
    stages: [
      { step: 1, name: '前四排声母速推', detail: 'bpmf dtnl gkh jqx 连贯点击' },
      { step: 2, name: '平翘舌音清醒辨认', detail: 'zh ch sh r z c s 区分明晰' },
      { step: 3, name: 'y w 零失误收官', detail: '最后两音顺利命中' },
    ],
  },
  {
    id: 'plan-051',
    level: 51,
    category: 'reading',
    title: '5×5 同心圆千字文全息扫读',
    subtitle: '同心圆盘 + 千字文韵律 · 突破方正阅读局限',
    tag: '圆盘千字文',
    tagColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    icon: '🌀',
    difficulty: 4,
    audience: '希望培养全景速读能力、摆脱横平竖直阅读狭隘视野的读者',
    prescription: '读书前练习 1 组，让汉字在全景环形视野中瞬间浮现',
    brainTarget: '非线性阅读视野重构，激发右脑图像式汉字整体摄入',
    desc: '在同心圆阵列中寻找千字文，打破常规左至右的阅读动线，极大拓宽阅读扫视广度。',
    targetDuration: '目标: 5×5 圆盘千字文 < 30 秒',
    config: { size: 5, shape: 'circle', mode: 'chinese_chars', centerFocusDot: true },
    stages: [
      { step: 1, name: '圆心文字凝视', detail: '中心点定睛，余光向外圈汉字延展' },
      { step: 2, name: '环形语感搜寻', detail: '顺应千字文韵文语流，在不同同心圆上捕字' },
      { step: 3, name: '全息图像摄入', detail: '将汉字作为图形整体，直觉点击' },
    ],
  },
  {
    id: 'plan-052',
    level: 52,
    category: 'reading',
    title: '5×5 蜂巢错位古诗绝句寻踪',
    subtitle: '蜂窝六边形 + 唐诗绝句 · 意境与非对称错位融合',
    tag: '蜂巢唐诗',
    tagColor: 'bg-amber-100 text-amber-800 border-amber-300',
    icon: '🐝',
    difficulty: 4,
    audience: '追求文学审美与脑力挑战并重的国风学者与诗词达人',
    prescription: '练习时在脑中轻吟诗意，随蜂窝错位节奏逐字追寻',
    brainTarget: '意境语义加工网络与复杂错位几何视觉的跨模态融合',
    desc: '在 25 个六边形蜂窝单元中追寻绝句诗句，既有古风的儒雅，又有现代几何的敏锐。',
    targetDuration: '目标: 5×5 蜂巢唐诗 < 28 秒',
    config: { size: 5, shape: 'honeycomb', mode: 'chinese_poetry', centerFocusDot: false },
    stages: [
      { step: 1, name: '首句诗眼起航', detail: '根据诗题在蜂窝交错中锁定首字' },
      { step: 2, name: '错位诗行跨越', detail: '诗句跨行时在对角蜂窝间平滑过渡' },
      { step: 3, name: '整篇浑然天成', detail: '末字落定，全诗意境在胸中升腾' },
    ],
  },
  {
    id: 'plan-053',
    level: 53,
    category: 'reading',
    title: '6×6 千字文国风宏大卷轴',
    subtitle: '36 格千字文长文段 · 高密度汉字图形瞬时解码',
    tag: '宏大卷轴',
    tagColor: 'bg-slate-900 text-emerald-300 border-slate-700',
    icon: '📖',
    difficulty: 5,
    audience: '专业速读选手 · 中文系学者 · 需高通量阅读文献的学术工作者',
    prescription: '每周练习 2 次，体会一目十行、整体字形飞速摄入的超快感',
    brainTarget: '大脑左枕颞叶“文字盒区”（Visual Word Form Area）高负荷吞吐',
    desc: '整整 36 个千字文汉字密密麻麻排布，要求完全跳过心中发音，凭字形整体图像瞬间锁定。',
    targetDuration: '目标: 6×6 千字文 < 48 秒',
    config: { size: 6, shape: 'grid', mode: 'chinese_chars', centerFocusDot: false },
    stages: [
      { step: 1, name: '前 12 字行云流水', detail: '天地玄黄宇宙洪荒日月盈昃' },
      { step: 2, name: '中 12 字稳准扫描', detail: '辰宿列张寒来暑往秋收冬藏' },
      { step: 3, name: '后 12 字疾速收官', detail: '闰余成岁律吕调阳云腾致雨' },
    ],
  },
  {
    id: 'plan-054',
    level: 54,
    category: 'reading',
    title: '6×6 成语连环博览群书',
    subtitle: '36 格成语长河 · 九组经典成语连绵接力',
    tag: '成语博览',
    tagColor: 'bg-amber-100 text-amber-900 border-amber-300',
    icon: '🏮',
    difficulty: 5,
    audience: '语文培优生 · 成语爱好者 · 需保持持久高密度语言专注力者',
    prescription: '深度脑力写作前练习 1 组，全面润滑语言词库通道',
    brainTarget: '词语序列长链条提取与大空间字形定位协同',
    desc: '36 格涵盖 9 个成语的连环接力，要求全程保持高强度的词汇注意力与定位敏锐度。',
    targetDuration: '目标: 6×6 成语长河 < 50 秒',
    config: { size: 6, shape: 'grid', mode: 'chinese_idioms', centerFocusDot: false },
    stages: [
      { step: 1, name: '成语长河开篇', detail: '前 3 组四字成语稳步连击' },
      { step: 2, name: '中流砥柱稳步推进', detail: '克服字符密集带来的视觉杂乱' },
      { step: 3, name: '终成正果完成全部', detail: '顺利点完第 36 字' },
    ],
  },

  // =========================================================================
  // 4. 瞬时记忆与算力突破学院 (L55 - L72)
  // =========================================================================
  {
    id: 'plan-055',
    level: 55,
    category: 'cognitive',
    title: '3×3 脑内拍照微盲打体验',
    subtitle: '9 格闪现 3 秒后隐退 · 初探空间心智地图',
    tag: '微盲打启蒙',
    tagColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    icon: '👁️',
    difficulty: 2,
    audience: '从未尝试过盲打模式 · 欲测试自己瞬时空间记忆的初学者',
    prescription: '连练 3 次，感受字符隐去后脑中留存的“残影心智地图”',
    brainTarget: '视觉感觉记忆（Iconic Memory）向短时工作记忆的转存',
    desc: '9 个方格在短暂展示后隐去内容，仅凭几秒内的脑内快照，完成 1 到 9 的纯盲打点击。',
    targetDuration: '目标: 3×3 盲打零失误通关',
    config: { size: 3, shape: 'grid', mode: 'blind_memory', centerFocusDot: false },
    stages: [
      { step: 1, name: '3秒脑内快照', detail: '开局瞬间扫视 9 个位置，印在脑海' },
      { step: 2, name: '字符隐去盲击', detail: '屏幕变暗后凭空间位置记忆稳妥点击' },
      { step: 3, name: '建立空间信心', detail: '顺利通关，建立空间心智地图信心' },
    ],
  },
  {
    id: 'plan-056',
    level: 56,
    category: 'cognitive',
    title: '3×3 晨间心算速决小测验',
    subtitle: '9 道基础加减算式 · 激活顶叶心算通路',
    tag: '心算速决',
    tagColor: 'bg-yellow-100 text-yellow-800 border-yellow-300',
    icon: '🧮',
    difficulty: 2,
    audience: '感觉大脑算力生锈 · 需快速热身心算与数字敏锐度者',
    prescription: '晨起练习 2 组，如同给大脑核心 CPU 做热身拉伸',
    brainTarget: '顶叶双侧内侧沟（IPS）对数量符号的快速心算求值',
    desc: '方格显示形如 2+3 或 7-4 的算式，按结果 1 到 9 依次搜寻匹配项，手脑并用。',
    targetDuration: '目标: 3×3 心算 < 8 秒',
    config: { size: 3, shape: 'grid', mode: 'math_calc', centerFocusDot: false },
    stages: [
      { step: 1, name: '目标数定位', detail: '当前目标是 1，迅速寻找结果为 1 的算式' },
      { step: 2, name: '心算过滤排除', detail: '排除算式中出现 1 但结果非 1 的诱导' },
      { step: 3, name: '流水式通关', detail: '9 道算式连击通过' },
    ],
  },
  {
    id: 'plan-057',
    level: 57,
    category: 'cognitive',
    title: '4×4 瞬时记忆与盲打隐退挑战',
    subtitle: '16 格闪现记忆隐退 · 挑战空间大脑地图',
    tag: '空间盲打',
    tagColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    icon: '👁️',
    difficulty: 4,
    audience: '脑力极限挑战者 · 欲提升瞬时视觉工作记忆与空间想象力',
    prescription: '每日挑战 1 组，记录在隐退状态下的准确通关率',
    brainTarget: '开局 4 秒内迅速对棋盘进行脑内快照，依靠空间心智模型盲打',
    desc: '开局后棋盘仅短暂停留几秒随后隐去字符，凭借短暂视觉记忆与空间坐标完成点击。',
    targetDuration: '目标: 4×4 盲打隐退零失误通关',
    config: { size: 4, shape: 'grid', mode: 'blind_memory', centerFocusDot: false },
    stages: [
      { step: 1, name: '4秒全景拍照', detail: '开局倒计时内快速扫视，将1-16数字的大致区块印入脑海' },
      { step: 2, name: '心智空间映射', detail: '字符隐去后，依据脑内留存的空间坐标记忆沉着点击' },
      { step: 3, name: '排除遗忘干扰', detail: '遭遇局部模糊时通过排除法逻辑推理，完成盲打闭环' },
    ],
  },
  {
    id: 'plan-058',
    level: 58,
    category: 'cognitive',
    title: '4×4 心算速算与目标检索并进',
    subtitle: '16 道算术心算 · 激活大脑顶叶与前额叶并发',
    tag: '心算速查',
    tagColor: 'bg-yellow-100 text-yellow-800 border-yellow-300',
    icon: '🧮',
    difficulty: 3,
    audience: '需兼顾心算推导与眼动搜寻的职场人群、学生与分析师',
    prescription: '练习 2 组，全面调动心算与视觉并发处理能力',
    brainTarget: '口算求值与视野中匹配算式同步并发处理，强化高阶算力',
    desc: '每个方块显示一条算式（如 2+3 或 12-4），按结果序列依次寻找匹配算式。',
    targetDuration: '目标: 4×4 速算 < 18 秒',
    config: { size: 4, shape: 'grid', mode: 'math_calc', centerFocusDot: false },
    stages: [
      { step: 1, name: '双通道并行处理', detail: '大脑一边进行加减心算，一边在视野中排查对应算式' },
      { step: 2, name: '抑制干扰数值', detail: '排除算式中与目标数字相同但结果不符的数字干扰' },
      { step: 3, name: '建立心算心流', detail: '随着连击建立快速的数字敏感度与心算直觉' },
    ],
  },
  {
    id: 'plan-059',
    level: 59,
    category: 'cognitive',
    title: '4×4 同心圆盲打空间重构',
    subtitle: '圆盘同心放射 + 记忆隐退 · 挑战极坐标脑图',
    tag: '圆盘盲打',
    tagColor: 'bg-sky-100 text-sky-800 border-sky-300',
    icon: '🌀',
    difficulty: 4,
    audience: '方形盲打游刃有余 · 欲挑战非笛卡尔坐标空间记忆者',
    prescription: '练习 1 组，以同心圆内外半径为锚点建立心智模型',
    brainTarget: '海马体空间位置细胞（Place Cells）对极坐标环境的编码',
    desc: '在同心圆阵列中短暂停留后隐退，按极坐标半径与角度凭记忆盲点。',
    targetDuration: '目标: 4×4 圆盘盲打完成度 > 90%',
    config: { size: 4, shape: 'circle', mode: 'blind_memory', centerFocusDot: true },
    stages: [
      { step: 1, name: '内圈与外圈锚定', detail: '开局迅速分清内圈与外圈的数字分布' },
      { step: 2, name: '角度顺时针印刻', detail: '脑中形成时钟指针般的顺时针方位残影' },
      { step: 3, name: '定心盲点通关', detail: '沉稳点击隐退圆盘，完成空间盲打' },
    ],
  },
  {
    id: 'plan-060',
    level: 60,
    category: 'cognitive',
    title: '4×4 菱形斜角心算矩阵',
    subtitle: '45° 倾斜对角 + 心算速算 · 空间与计算双压',
    tag: '斜角速算',
    tagColor: 'bg-amber-100 text-amber-800 border-amber-300',
    icon: '💠',
    difficulty: 4,
    audience: '高难度复合训练需求者 · 需全面提升抗压算力者',
    prescription: '每周练习 2-3 次，在斜向几何空间中自如心算',
    brainTarget: '顶下小叶空间旋转运算与顶内沟数值运算的协同交织',
    desc: '在 45 度菱形排布中完成 16 道算式心算匹配，打破水平阅读惯性，激发复合算力。',
    targetDuration: '目标: 4×4 菱形心算 < 20 秒',
    config: { size: 4, shape: 'diamond', mode: 'math_calc', centerFocusDot: true },
    stages: [
      { step: 1, name: '适应斜向排布', detail: '快速浏览菱形四角与中心的算式' },
      { step: 2, name: '心算结果与对角匹配', detail: '克服倾斜带来的阅读迟滞，迅速命中' },
      { step: 3, name: '顺畅连击完赛', detail: '零失误通过全部 16 项心算' },
    ],
  },
  {
    id: 'plan-061',
    level: 61,
    category: 'cognitive',
    title: '4×4 蜂巢交错盲打熔炉',
    subtitle: '蜂窝错位几何 + 盲打隐退 · 挑战六角拓扑记忆',
    tag: '蜂巢盲打',
    tagColor: 'bg-purple-100 text-purple-800 border-purple-300',
    icon: '🐝',
    difficulty: 5,
    audience: '顶尖空间认知高手 · 欲突破常规几何记忆极限者',
    prescription: '每周挑战 1 次，在六边形交错中构建稳固的拓扑记忆网',
    brainTarget: '内嗅皮层网格细胞（Grid Cells）对六边形几何的高效利用',
    desc: '蜂窝六边形错位排布隐退后凭记忆盲点，探索生物界最神奇的网格细胞本能记忆。',
    targetDuration: '目标: 4×4 蜂巢盲打通关',
    config: { size: 4, shape: 'honeycomb', mode: 'blind_memory', centerFocusDot: false },
    stages: [
      { step: 1, name: '六角相邻关系记忆', detail: '记住数字彼此之间的相邻蜂窝关系' },
      { step: 2, name: '隐退后顺藤摸瓜', detail: '以已知锚点推导相邻隐退方块数值' },
      { step: 3, name: '精密盲击收盘', detail: '在蜂窝错位中全部命中' },
    ],
  },
  {
    id: 'plan-062',
    level: 62,
    category: 'cognitive',
    title: '4×4 星象散落自由心算',
    subtitle: '散落星象非对称 + 心算速算 · 纯粹空间算力',
    tag: '散落速算',
    tagColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    icon: '✨',
    difficulty: 4,
    audience: '需训练复杂无序界面下的敏锐心算抓取能力者',
    prescription: '练习 2 组，锻炼在任意方位瞬间完成算式求值匹配',
    brainTarget: '无规则空间注意力分配与心算求值的即时响应',
    desc: '算式如星辰般不规则散布，完全脱离网格行列辅助，全凭空间直觉与心算并发。',
    targetDuration: '目标: 4×4 散落心算 < 20 秒',
    config: { size: 4, shape: 'scatter', mode: 'math_calc', centerFocusDot: true },
    stages: [
      { step: 1, name: '自由全景视野', detail: '将视野展开为整体，不被网格所束缚' },
      { step: 2, name: '目标数值即时定位', detail: '心里一算出得数，立刻在散点中锁定' },
      { step: 3, name: '自由轨迹通关', detail: '顺着自由轨迹连击完成' },
    ],
  },
  {
    id: 'plan-063',
    level: 63,
    category: 'cognitive',
    title: '5×5 高阶脑内快照盲打',
    subtitle: '25 格高难度空间记忆 · 顶尖视觉工作记忆熔炉',
    tag: '高阶盲打',
    tagColor: 'bg-purple-100 text-purple-800 border-purple-300',
    icon: '🧠',
    difficulty: 5,
    audience: '常态 4×4 轻松通关的高手 · 追求超凡记忆广度的挑战者',
    prescription: '每周练习 2 次，建议分区域（左上/右下）模块化编码记忆',
    brainTarget: '挑战工作记忆容量极限（常规人类瞬时容量约 7±2 个信息块）',
    desc: '在 25 格复杂盘面隐退后凭记忆完成点选，突破常规人脑短时记忆极限容量。',
    targetDuration: '目标: 5×5 盲打完成度 > 85%',
    config: { size: 5, shape: 'grid', mode: 'blind_memory', centerFocusDot: false },
    stages: [
      { step: 1, name: '区块化切片记忆', detail: '将 25 格划分为四个角与中心十字分别扫描' },
      { step: 2, name: '关键锚点定位', detail: '优先锁定 1、5、10、15、20、25 等关键里程碑位置' },
      { step: 3, name: '沉着推演盲击', detail: '字符隐去后屏气凝神，依靠残存印迹逐一还原' },
    ],
  },
  {
    id: 'plan-064',
    level: 64,
    category: 'cognitive',
    title: '5×5 算术速算大盘高压心算',
    subtitle: '25 道复杂算式连续心算 · 极速脑力马拉松',
    tag: '大盘心算',
    tagColor: 'bg-yellow-100 text-yellow-800 border-yellow-300',
    icon: '🧮',
    difficulty: 4,
    audience: '金融交易员 · 数学竞赛备考生 · 需保持超强抗压算力者',
    prescription: '每周练习 2-3 次，体验连续 25 题高强度心算的深度心流',
    brainTarget: '顶叶双侧算力中枢与前额叶工作记忆在长周期下的抗疲劳维持',
    desc: '25 个方格全部为算式，按 1 至 25 顺序依次寻找对应算式，极度考察心算稳定性。',
    targetDuration: '目标: 5×5 心算大盘 < 36 秒',
    config: { size: 5, shape: 'grid', mode: 'math_calc', centerFocusDot: false },
    stages: [
      { step: 1, name: '1-8 基础算式速决', detail: '保持平缓呼吸，快速找出前 8 项' },
      { step: 2, name: '9-18 中段算力相持', detail: '面对两位数加减乘除心算，沉着应对' },
      { step: 3, name: '19-25 冲刺攻坚', detail: '克服大脑算力疲劳，稳定击中收官' },
    ],
  },
  {
    id: 'plan-065',
    level: 65,
    category: 'cognitive',
    title: '5×5 爱心轮廓空间记忆盲打',
    subtitle: '爱心弧度 + 记忆隐退 · 有机边界空间心智模型',
    tag: '心形盲打',
    tagColor: 'bg-rose-100 text-rose-800 border-rose-300',
    icon: '❤️',
    difficulty: 5,
    audience: '欲在有机不规则空间中测试高级工作记忆的高手',
    prescription: '每周练习 1 组，将记忆与优美的心形轮廓完美结合',
    brainTarget: '顶叶对复杂有机边界内散点的空间记忆重塑',
    desc: '心形轮廓隐退后，依仗对心尖、双弧和中央核心的方位印迹完成盲打挑战。',
    targetDuration: '目标: 5×5 爱心盲打完成度 > 80%',
    config: { size: 5, shape: 'heart', mode: 'blind_memory', centerFocusDot: true },
    stages: [
      { step: 1, name: '轮廓三区记忆', detail: '将爱心分为上部双翼、中间腹地与下部心尖' },
      { step: 2, name: '特征数字绑定', detail: '将首末关键数字与轮廓显著特征点绑定' },
      { step: 3, name: '凭心而击通关', detail: '字符隐退后沉着点按，见证超凡记忆' },
    ],
  },
  {
    id: 'plan-066',
    level: 66,
    category: 'cognitive',
    title: '5×5 五角星芒极点盲打',
    subtitle: '星芒放射 + 记忆隐退 · 挑战五极跳跃空间记忆',
    tag: '星芒盲打',
    tagColor: 'bg-amber-100 text-amber-800 border-amber-300',
    icon: '⭐',
    difficulty: 5,
    audience: '空间想象力顶尖极客 · 欲挑战极限跳视空间记忆者',
    prescription: '练习时注意在心中画出五角星连接线，以线条为线索回忆',
    brainTarget: '跨大跨距尖点跳跃的表象心理旋转与空间暂存',
    desc: '五角星尖端向五个方向散开，隐退后全凭脑海中保留的五角星残像进行大跨度盲点。',
    targetDuration: '目标: 5×5 星芒盲打通关',
    config: { size: 5, shape: 'star', mode: 'blind_memory', centerFocusDot: true },
    stages: [
      { step: 1, name: '五星尖芒印记', detail: '牢固记住分布在五个尖端的数字' },
      { step: 2, name: '中心星核定位', detail: '记住内部星核区域数字坐标' },
      { step: 3, name: '大跨度精准盲点', detail: '在黑暗中自如跳跃，准确通关' },
    ],
  },
  {
    id: 'plan-067',
    level: 67,
    category: 'cognitive',
    title: '5×5 螺旋星系心算循迹',
    subtitle: '阿基米德旋涡 + 心算速算 · 环形流线中飞速求值',
    tag: '螺旋速算',
    tagColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    icon: '🪐',
    difficulty: 4,
    audience: '需训练在动态轨迹中保持精准逻辑计算的工程师与数据专家',
    prescription: '练习 1-2 组，体验旋涡轨迹与心算节奏的完美融合',
    brainTarget: '连续曲线追踪与离散数值匹配的神经元并发处理',
    desc: '在阿基米德螺旋轨道上分布 25 道算式，目光随旋转轨迹流动的同时完成连续心算。',
    targetDuration: '目标: 5×5 螺旋速算 < 38 秒',
    config: { size: 5, shape: 'spiral', mode: 'math_calc', centerFocusDot: true },
    stages: [
      { step: 1, name: '旋涡内圈起步', detail: '从旋涡中心迅速完成前几道算式' },
      { step: 2, name: '顺轨向外扩散', detail: '沿螺旋轨迹向外扩大扫视范围' },
      { step: 3, name: '最外环从容收尾', detail: '外圈算式逐一求解并命中' },
    ],
  },
  {
    id: 'plan-068',
    level: 68,
    category: 'cognitive',
    title: '5×5 蝶翼双环跨半球盲打',
    subtitle: '左右双翼 + 记忆隐退 · 考验左右半脑协同空间记忆',
    tag: '双翼盲打',
    tagColor: 'bg-purple-100 text-purple-800 border-purple-300',
    icon: '🦋',
    difficulty: 5,
    audience: '脑力运动健将 · 欲测试左右脑跨半球工作记忆协同者',
    prescription: '每周 1 次，左右半场交替提取空间印迹',
    brainTarget: '胼胝体在空间感觉记忆提取过程中的双向高速中继',
    desc: '蝴蝶双翼空间布局隐退后盲打，要求左视野与右视野空间记忆紧密联动。',
    targetDuration: '目标: 5×5 双翼盲打完成度 > 85%',
    config: { size: 5, shape: 'butterfly', mode: 'blind_memory', centerFocusDot: true },
    stages: [
      { step: 1, name: '左翼与右翼分屏记忆', detail: '在脑内建立左半屏与右半屏双重快照' },
      { step: 2, name: '中央脊柱对称校验', detail: '利用中心对称轴校准左右位置' },
      { step: 3, name: '跨半球从容点击', detail: '盲打时左右穿梭，零失误通过' },
    ],
  },
  {
    id: 'plan-069',
    level: 69,
    category: 'cognitive',
    title: '5×5 十字经纬心算排查',
    subtitle: '十字星阵四象限 + 心算速算 · 严谨经纬度算力排查',
    tag: '十字速算',
    tagColor: 'bg-blue-100 text-blue-800 border-blue-300',
    icon: '➕',
    difficulty: 4,
    audience: '习惯系统化逻辑排查 · 需提升矩阵运算敏锐度者',
    prescription: '工作前练习 1 组，迅速建立有条不紊的算力思维',
    brainTarget: '四象限空间几何结构与心算结果匹配网络',
    desc: '沿横竖两轴分布算式，四象限内心算求值与坐标匹配相辅相成，严谨扎实。',
    targetDuration: '目标: 5×5 十字速算 < 36 秒',
    config: { size: 5, shape: 'cross', mode: 'math_calc', centerFocusDot: true },
    stages: [
      { step: 1, name: '四端极点算式排查', detail: '优先计算并确认十字最外侧算式' },
      { step: 2, name: '四象限逐一清扫', detail: '由外向内逐步计算命中' },
      { step: 3, name: '十字核心撞线', detail: '中心算式稳准解决，通关成功' },
    ],
  },
  {
    id: 'plan-070',
    level: 70,
    category: 'cognitive',
    title: '5×5 波浪流水动态盲打',
    subtitle: 'S型流水蜿蜒 + 记忆隐退 · 挑战曲线轨迹残留表象',
    tag: '波浪盲打',
    tagColor: 'bg-cyan-100 text-cyan-800 border-cyan-300',
    icon: '〰️',
    difficulty: 5,
    audience: '高阶记忆达人 · 欲测试曲线动态流场表象保持能力者',
    prescription: '练习时在脑海中勾勒出完整的 S 弯道水流，按水流流向追忆',
    brainTarget: '顶叶后部对弯曲运动轨迹的动态脑内模拟与再现',
    desc: 'S型蜿蜒蛇形排列，在字符隐退后依仗波浪轨迹在脑海中留下的残影盲点击。',
    targetDuration: '目标: 5×5 波浪盲打完成度 > 85%',
    config: { size: 5, shape: 'wave', mode: 'blind_memory', centerFocusDot: true },
    stages: [
      { step: 1, name: '捕捉 S 弯道走势', detail: '开局迅速顺着波浪走向记住节点次序' },
      { step: 2, name: '波峰波谷锚点确定', detail: '将关键数字锚定在极值弯道上' },
      { step: 3, name: '顺流而下盲点通关', detail: '字符隐去后如行云流水般点击完成' },
    ],
  },
  {
    id: 'plan-071',
    level: 71,
    category: 'cognitive',
    title: '6×6 极限脑内全景盲打',
    subtitle: '36 格超高难度空间记忆 · 探索人脑工作记忆天花板',
    tag: '36格极限盲打',
    tagColor: 'bg-slate-900 text-purple-300 border-slate-700',
    icon: '🧠',
    difficulty: 5,
    audience: '世界脑力记忆大师选手 · 追求认知巅峰的极限挑战极客',
    prescription: '每月挑战 1-2 次，探索自我心智在超高负荷下的奇迹潜能',
    brainTarget: '工作记忆容量极限超载、海马体与前额叶深层突触协同强化',
    desc: '整整 36 个方格隐退！对人类常规工作记忆极限的巨大挑战，考验真正的空间结构化编码能力。',
    targetDuration: '目标: 6×6 盲打完成度 > 75%',
    config: { size: 6, shape: 'grid', mode: 'blind_memory', centerFocusDot: false },
    stages: [
      { step: 1, name: '全盘结构化切片', detail: '将 36 格划分为九宫格或四个象限分别快速编码' },
      { step: 2, name: '关键数字骨架支撑', detail: '优先建立 1, 10, 20, 30, 36 骨架坐标' },
      { step: 3, name: '气沉丹田极度专注盲击', detail: '排除一切外界声光杂念，依靠心神投影逐一命中' },
    ],
  },
  {
    id: 'plan-072',
    level: 72,
    category: 'cognitive',
    title: '6×6 心算速算全域长征',
    subtitle: '36 道复杂算式连续求值 · 挑战大脑耐力与算力极限',
    tag: '心算长征',
    tagColor: 'bg-yellow-100 text-yellow-900 border-yellow-300',
    icon: '🧮',
    difficulty: 5,
    audience: '顶级算力追求者 · 需要超长高强度精准数字决策的领航者',
    prescription: '精力充沛时练习 1 组，体验连续 36 题高压心算的沉浸快感',
    brainTarget: '顶内沟与额中回在极长运算周期下的强韧性与持续供能',
    desc: '36 道算式从 1 连续心算求解至 36，不仅是速度考验，更是绝不犯错的心算耐力长征。',
    targetDuration: '目标: 6×6 心算长征 < 60 秒',
    config: { size: 6, shape: 'grid', mode: 'math_calc', centerFocusDot: false },
    stages: [
      { step: 1, name: '1-12 步平稳铺垫', detail: '迅速完成前 12 道算式，建立稳定算力手感' },
      { step: 2, name: '13-24 步抗心算疲劳', detail: '中段克服脑力疲倦，保持精准求值' },
      { step: 3, name: '25-36 步意志坚守', detail: '后程顶住压力，以零失误完成长征' },
    ],
  },

  // =========================================================================
  // 5. 视知觉与抗干扰追踪学院 (L73 - L88)
  // =========================================================================
  {
    id: 'plan-073',
    level: 73,
    category: 'stroop',
    title: '3×3 纯非语言几何符号知觉',
    subtitle: '9 种几何星象符号 · 剥离语义的纯视觉特征比对',
    tag: '几何知觉',
    tagColor: 'bg-amber-100 text-amber-800 border-amber-300',
    icon: '★',
    difficulty: 1,
    audience: '想要摆脱数字与文字依赖 · 训练纯粹视网膜图形匹配的人群',
    prescription: '每日 2 组，感受几何图形在眼前瞬间识别的直观魅力',
    brainTarget: '视觉联合区（V2/V4）对几何形状、角点和拓扑特征的快速提取',
    desc: '★, ●, ▲, ■, ◆... 剥离语言语义，仅凭纯粹的非语言几何形状特征迅速搜索匹配。',
    targetDuration: '目标: 3×3 符号 < 4.5 秒',
    config: { size: 3, shape: 'grid', mode: 'symbols', centerFocusDot: false },
    stages: [
      { step: 1, name: '符号特征感知', detail: '将五角星、圆形、三角形等作为纯图形输入' },
      { step: 2, name: '形态直接匹配', detail: '看到目标符号瞬间在盘面捕捉对应轮廓' },
      { step: 3, name: '连击完赛', detail: '9 个符号流水般快速通过' },
    ],
  },
  {
    id: 'plan-074',
    level: 74,
    category: 'stroop',
    title: '3×3 动态微移重排启蒙',
    subtitle: '每次点击后邻近卡牌微移 · 破除死记硬背',
    tag: '动态微移',
    tagColor: 'bg-violet-100 text-violet-800 border-violet-300',
    icon: '⚡',
    difficulty: 2,
    audience: '习惯死记硬背固定位置 · 遇到外部变动容易慌乱者',
    prescription: '每日 2 组，学会接纳位置动态刷新，以敏锐眼动取代死板记忆',
    brainTarget: '适应动态变迁环境，前扣带回实时调整视觉关注策略',
    desc: '每成功点击一次，盘面未点方块就会轻微滑动重排，强迫你随时随地进行即时搜索。',
    targetDuration: '目标: 3×3 动态重排 < 5 秒',
    config: { size: 3, shape: 'grid', mode: 'dynamic_shift', centerFocusDot: false },
    stages: [
      { step: 1, name: '接受微位移扰动', detail: '方块滑动后不慌张，视线迅速重聚当前目标' },
      { step: 2, name: '即时动态捕捉', detail: '以敏捷的即时扫视取代死记硬背' },
      { step: 3, name: '流畅击发', detail: '快速完成 9 个动态目标点击' },
    ],
  },
  {
    id: 'plan-075',
    level: 75,
    category: 'stroop',
    title: '4×4 几何星象特征辨识进阶',
    subtitle: '16 种丰富几何星象符号 · 纯视觉模式匹配',
    tag: '星象模式',
    tagColor: 'bg-amber-100 text-amber-800 border-amber-300',
    icon: '✦',
    difficulty: 2,
    audience: 'UI/视觉设计师 · 建筑测绘员 · 需提升非文字图形敏感度者',
    prescription: '练习 2 组，强化对不同象形符号微细差异的瞬时捕捉',
    brainTarget: '下颞叶（IT cortex）复杂形状表征神经元的精细调谐',
    desc: '涵盖五瓣花、六角形、十字星、黑桃、红心、光轮等 16 种精美符号，纯视觉比对。',
    targetDuration: '目标: 4×4 符号 < 12 秒',
    config: { size: 4, shape: 'grid', mode: 'symbols', centerFocusDot: false },
    stages: [
      { step: 1, name: '图形特征速览', detail: '提前扫视盘面中各种特殊图形的位置' },
      { step: 2, name: '目标特征瞬时锁定', detail: '根据上方提示符号，迅速找到对应图形' },
      { step: 3, name: '消除视觉混淆', detail: '区分相似的星形与花形，准确通关' },
    ],
  },
  {
    id: 'plan-076',
    level: 76,
    category: 'stroop',
    title: '4×4 光谱色彩波长辨色',
    subtitle: '赤橙黄绿青蓝紫渐变 · 锻炼视网膜色相敏感度',
    tag: '光谱渐变',
    tagColor: 'bg-rose-100 text-rose-800 border-rose-300',
    icon: '🌈',
    difficulty: 3,
    audience: '美术设计从业者 · 摄影师 · 调色师 · 想要提升色彩敏锐度者',
    prescription: '每日练习 2 组，感受目光在彩虹连续光谱波长中的自然流淌',
    brainTarget: '视皮层 V4 区色相处理柱（Color Blobs）的兴奋与微细分辨率提升',
    desc: '按彩虹光谱波长与色相由红至紫依次寻找，锻炼视网膜锥状细胞与视皮层色敏度。',
    targetDuration: '目标: 4×4 光谱渐变 < 13 秒',
    config: { size: 4, shape: 'grid', mode: 'color_gradient', centerFocusDot: false },
    stages: [
      { step: 1, name: '暖色调起始', detail: '由赤红、橙红、琥珀、亮黄温暖起步' },
      { step: 2, name: '中性绿蓝过渡', detail: '顺应光谱平滑过渡至青柠、翠绿、天蓝、湛蓝' },
      { step: 3, name: '冷艳紫粉收官', detail: '在靛青、幽紫、洋红、赤玫中完成光谱闭环' },
    ],
  },
  {
    id: 'plan-077',
    level: 77,
    category: 'stroop',
    title: '4×4 斯特鲁普色彩抗干扰心理学测试',
    subtitle: '色彩与文字字义冲突 · 强行压制自动化阅读诱惑',
    tag: 'Stroop效应',
    tagColor: 'bg-rose-100 text-rose-800 border-rose-300',
    icon: '🎨',
    difficulty: 4,
    audience: '容易被无关视觉噪音分散精力 · 决策犹豫不决者',
    prescription: '精神涣散或容易被外界打断时练习 1-2 组，找回绝对把控感',
    brainTarget: '前扣带回皮层（ACC）强烈激活，压制颜色感知的自动加工优势',
    desc: '文字字义与字体呈现颜色产生剧烈冲突，要求只根据提示颜色决断，排除字义干扰。',
    targetDuration: '目标: 4×4 斯特鲁普零失误 < 15 秒',
    config: { size: 4, shape: 'grid', mode: 'stroop_color', centerFocusDot: false },
    stages: [
      { step: 1, name: '抑制字义直觉', detail: '看到写着“蓝”但实际是红色的字时，只关注提示目标颜色' },
      { step: 2, name: '维持从容节奏', detail: '在色彩与字义冲突中保持冷静呼吸，杜绝冲动乱点' },
      { step: 3, name: '零失误高准通关', detail: '训练严苛的认知控制力，做到全过程零错误' },
    ],
  },
  {
    id: 'plan-078',
    level: 78,
    category: 'stroop',
    title: '4×4 动态位移抗漂移追踪',
    subtitle: '点击后未选方块随机重排 · 应对复杂动态变数',
    tag: '动态微移',
    tagColor: 'bg-violet-100 text-violet-800 border-violet-300',
    icon: '⚡',
    difficulty: 4,
    audience: '面对变化容易心烦意乱 · 需训练动态适应力与敏锐眼动者',
    prescription: '进阶挑战 1-2 组，锻炼在非稳态环境下的抗扰追踪定力',
    brainTarget: '不依赖静态死记硬背位置，随时对新排布做出即时刷新与适应',
    desc: '每次成功点击后，其余未点击方块会发生随机轻微位移换位，考察应对变数的能力。',
    targetDuration: '目标: 4×4 动态换位 < 16 秒',
    config: { size: 4, shape: 'grid', mode: 'dynamic_shift', centerFocusDot: false },
    stages: [
      { step: 1, name: '接受动态扰动', detail: '方块换位后不慌不乱，视线迅速重聚当前目标' },
      { step: 2, name: '摒弃死记硬背', detail: '以敏捷的即时扫视取代静态记忆，适应位置变迁' },
      { step: 3, name: '动态捕捉连击', detail: '在变化中抓住瞬间机会，保持连贯的命中率' },
    ],
  },
  {
    id: 'plan-079',
    level: 79,
    category: 'stroop',
    title: '4×4 同心圆斯特鲁普双重抗扰',
    subtitle: '圆盘同心放射 + 色彩字义冲突 · 空间与色彩双重拉扯',
    tag: '圆盘Stroop',
    tagColor: 'bg-sky-100 text-sky-800 border-sky-300',
    icon: '🌀',
    difficulty: 4,
    audience: '抗干扰高手 · 需应对多重复杂视觉干扰环境者',
    prescription: '每周练习 2 次，在高难度视觉干扰下保持绝对定力',
    brainTarget: '前扣带回与空间注意顶叶网络的多维协同抗扰',
    desc: '打破方形行列，在同心圆形阵列中注入字色矛盾，既要克服圆周空间搜寻，又要过滤色彩欺骗。',
    targetDuration: '目标: 4×4 圆盘Stroop < 16 秒',
    config: { size: 4, shape: 'circle', mode: 'stroop_color', centerFocusDot: true },
    stages: [
      { step: 1, name: '定心同心圆', detail: '以中心红点为基准，展开辐射视野' },
      { step: 2, name: '精准过滤字色欺骗', detail: '不被字面文字带偏，直击目标颜色' },
      { step: 3, name: '圆周流畅通关', detail: '稳准狠完成全盘检索' },
    ],
  },
  {
    id: 'plan-080',
    level: 80,
    category: 'stroop',
    title: '4×4 蜂巢错位动态漂移追踪',
    subtitle: '蜂窝六边形 + 动态重排 · 应对六角网格下的动态微调',
    tag: '蜂巢动态',
    tagColor: 'bg-purple-100 text-purple-800 border-purple-300',
    icon: '🐝',
    difficulty: 4,
    audience: '高难度反应速度追求者 · 竞技游戏玩家与动态视力训练者',
    prescription: '练习 2 组，大幅提高对非线性动态位移的反射弧敏捷度',
    brainTarget: '复杂交错网格下的运动目标再检测与注视点即时重分配',
    desc: '蜂窝交错单元每次点中后轻微换位，考验眼球在蜂巢错位结构中的动态追踪速度。',
    targetDuration: '目标: 4×4 蜂巢动态 < 16 秒',
    config: { size: 4, shape: 'honeycomb', mode: 'dynamic_shift', centerFocusDot: false },
    stages: [
      { step: 1, name: '适应蜂窝微移', detail: '六边形卡块换位后迅速恢复聚焦' },
      { step: 2, name: '动态捕捉连击', detail: '捕捉移动后的目标数字' },
      { step: 3, name: '稳健完成通关', detail: '消除迟滞感，顺畅通过' },
    ],
  },
  {
    id: 'plan-081',
    level: 81,
    category: 'stroop',
    title: '5×5 纯视觉几何星象大盘',
    subtitle: '25 个全象形符号 · 彻底摆脱语言的纯粹眼动',
    tag: '星象大盘',
    tagColor: 'bg-amber-100 text-amber-800 border-amber-300',
    icon: '★',
    difficulty: 3,
    audience: '长时间脑力码字疲劳 · 欲给左脑语言中枢放假、唤醒右脑图形感者',
    prescription: '晚间练习 2 组，放松语言区，沉浸在纯净的几何美学中',
    brainTarget: '右脑顶颞皮层对图形空间构型与纹理特征的高维并行检索',
    desc: '全盘 25 个方格全部为纯几何与象形星芒符号，体验无需念出名字的纯粹图形感知。',
    targetDuration: '目标: 5×5 符号大盘 < 24 秒',
    config: { size: 5, shape: 'grid', mode: 'symbols', centerFocusDot: false },
    stages: [
      { step: 1, name: '图形直觉摄入', detail: '不用文字命名符号，纯凭图形感觉寻找' },
      { step: 2, name: '快速形态匹配', detail: '看到目标符号瞬间在盘面锁定对应图形' },
      { step: 3, name: '零失误大盘击穿', detail: '连贯无卡顿完成 25 项符号定位' },
    ],
  },
  {
    id: 'plan-082',
    level: 82,
    category: 'stroop',
    title: '5×5 经典斯特鲁普色彩抗干扰大考验',
    subtitle: '25 格全盘字色剧烈冲突 · 考验绝对冷静决断力',
    tag: '色彩抗干扰',
    tagColor: 'bg-rose-100 text-rose-800 border-rose-300',
    icon: '🎨',
    difficulty: 5,
    audience: '高压决策者 · 面对诱导性信息容易被带偏的谈判与分析人员',
    prescription: '每周练习 2-3 次，在激烈的视觉冲突中保持如止水般的定力',
    brainTarget: '额叶-扣带回执行网络对自动化冲动反应的绝对抑制与权威裁决',
    desc: '红字写着“蓝”、蓝字写着“黄”，25 次强烈的字色对抗，只看字体颜色，排除一切假象。',
    targetDuration: '目标: 5×5 斯特鲁普零失误 < 28 秒',
    config: { size: 5, shape: 'grid', mode: 'stroop_color', centerFocusDot: false },
    stages: [
      { step: 1, name: '建立色彩绝对标准', detail: '强令大脑只提取物理色彩，对文字语义完全失聪' },
      { step: 2, name: '中段抵御疲劳欺骗', detail: '在 10-20 项时保持高度清醒，严防冲动误触' },
      { step: 3, name: '百发百中完赛', detail: '以 100% 极高准确率终结比赛' },
    ],
  },
  {
    id: 'plan-083',
    level: 83,
    category: 'stroop',
    title: '5×5 动态位移抗漂移高阶追踪',
    subtitle: '25 格方块微移重排 · 应对复杂非稳态环境',
    tag: '动态重排',
    tagColor: 'bg-violet-100 text-violet-800 border-violet-300',
    icon: '⚡',
    difficulty: 5,
    audience: '需在瞬息万变环境中保持敏锐洞察的竞技选手与应急指挥员',
    prescription: '练习 1-2 组，培养随时随地重新建构视线焦点的能力',
    brainTarget: '大脑顶枕叶对动态变换场景的实时重定位与运动矢量消除',
    desc: '25 个方格在每次点击后发生随机微调漂移，死记硬背完全失效，全凭即时捕风捉影。',
    targetDuration: '目标: 5×5 动态重排 < 32 秒',
    config: { size: 5, shape: 'grid', mode: 'dynamic_shift', centerFocusDot: false },
    stages: [
      { step: 1, name: '戒除位置执念', detail: '点击后立即放开视野，重新快速搜索' },
      { step: 2, name: '即时动态锁定', detail: '利用余光敏锐捕捉移动后的目标' },
      { step: 3, name: '在变动中保持心流', detail: '适应非稳态节拍，连贯完成通关' },
    ],
  },
  {
    id: 'plan-084',
    level: 84,
    category: 'stroop',
    title: '5×5 爱心轮廓斯特鲁普色彩风暴',
    subtitle: '爱心有机轮廓 + 斯特鲁普字色冲突 · 美学与抗干扰结合',
    tag: '爱心Stroop',
    tagColor: 'bg-rose-100 text-rose-800 border-rose-300',
    icon: '❤️',
    difficulty: 5,
    audience: '追求独特美感与高强度抗干扰挑战的先锋认知学者',
    prescription: '每周练习 2 次，在有机爱心轮廓中保持纯粹色彩决断',
    brainTarget: '不规则曲线空间检索与前扣带回色彩冲突过滤的双重载荷',
    desc: '心形轮廓赋予视觉柔和的美感，但内部却涌动着激烈的字色冲突，考验柔中带刚的定力。',
    targetDuration: '目标: 5×5 爱心Stroop < 30 秒',
    config: { size: 5, shape: 'heart', mode: 'stroop_color', centerFocusDot: true },
    stages: [
      { step: 1, name: '心形边缘定睛', detail: '视线稳健穿梭在爱心各个区域' },
      { step: 2, name: '色彩穿透字义', detail: '只找目标颜色，无视心形内的字面含义' },
      { step: 3, name: '优雅收官', detail: '顺利通关，兼顾美感与极高专注度' },
    ],
  },
  {
    id: 'plan-085',
    level: 85,
    category: 'stroop',
    title: '5×5 星芒散落动态抗漂移',
    subtitle: '星象散落排布 + 动态微调漂移 · 彻底无序下的动态捕获',
    tag: '散落动态',
    tagColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    icon: '✨',
    difficulty: 5,
    audience: '极限动态视力追求者 · 极速反应力极限突破者',
    prescription: '精力充沛时练习 1 组，体验如同在浩瀚星空中抓取流星的爽快感',
    brainTarget: '无规则空间散点分布与动态位移矢量的双重综合解算',
    desc: '星象散落已经完全脱离网格，再加上每次点击后的微幅位移，是动态视力的顶级考场。',
    targetDuration: '目标: 5×5 散落动态 < 32 秒',
    config: { size: 5, shape: 'scatter', mode: 'dynamic_shift', centerFocusDot: true },
    stages: [
      { step: 1, name: '全景星空感知', detail: '不拘泥于特定方位，视线包容整个散落平面' },
      { step: 2, name: '动静即时捕捉', detail: '位移发生后眼动如闪电般迅速重捕' },
      { step: 3, name: '凌厉连击撞线', detail: '在星空变换中连击完赛' },
    ],
  },
  {
    id: 'plan-086',
    level: 86,
    category: 'stroop',
    title: '5×5 螺旋星系色彩抗扰旋涡',
    subtitle: '阿基米德旋涡 + 斯特鲁普字色冲突 · 旋转与色彩的双重幻境',
    tag: '螺旋Stroop',
    tagColor: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    icon: '🪐',
    difficulty: 5,
    audience: '高难度抗眩晕与抗干扰测试 · 飞行学员与极限运动者',
    prescription: '每周挑战 1 次，在旋转曲率与色彩诱导中立定脚跟',
    brainTarget: '前庭视觉联合区对旋转几何的自律抵抗与前扣带回抗诱惑',
    desc: '在旋转的阿基米德螺旋线路上注入字色矛盾，空间旋转与色彩欺骗双重来袭，考验磐石定力。',
    targetDuration: '目标: 5×5 螺旋Stroop < 32 秒',
    config: { size: 5, shape: 'spiral', mode: 'stroop_color', centerFocusDot: true },
    stages: [
      { step: 1, name: '稳住旋涡焦距', detail: '视线不被旋涡旋转带偏，立足中心' },
      { step: 2, name: '拨开色彩迷雾', detail: '穿透文字谎言，直视物理真色' },
      { step: 3, name: '旋风撞线', detail: '自中心至外环一气呵成通关' },
    ],
  },
  {
    id: 'plan-087',
    level: 87,
    category: 'stroop',
    title: '6×6 蜂巢错位色彩双重风暴',
    subtitle: '36 单元蜂窝六边形 + 斯特鲁普色彩双重抗扰',
    tag: '双重干扰',
    tagColor: 'bg-red-100 text-red-800 border-red-300',
    icon: '🌪️',
    difficulty: 5,
    audience: '高阶认知训练者 · 极限抗干扰与抗压决策人群',
    prescription: '每周练习 1-2 次，在高难度视觉干扰下保持绝对定力',
    brainTarget: '同时应对非直线交错蜂巢空间和激烈色彩冲突，全面压制冲动误点',
    desc: '在 36 个蜂窝错位单元中注入强烈的字色矛盾，挑战高级认知控制力的高峰。',
    targetDuration: '目标: 6×6 蜂巢双抗扰 < 48 秒',
    config: { size: 6, shape: 'honeycomb', mode: 'stroop_color', centerFocusDot: true },
    stages: [
      { step: 1, name: '立足中心基点', detail: '借助中心点稳定眼动，不被蜂窝错位带偏' },
      { step: 2, name: '双重过滤机制', detail: '既过滤颜色直觉欺骗，又克服六边形排列盲区' },
      { step: 3, name: '坚定从容决断', detail: '即使速度稍慢也要保证 100% 准确度' },
    ],
  },
  {
    id: 'plan-088',
    level: 88,
    category: 'stroop',
    title: '6×6 动态位移宏大追迹',
    subtitle: '36 格方块高频位移重排 · 极速适应动态未知',
    tag: '宏大动态',
    tagColor: 'bg-violet-900 text-amber-200 border-violet-700',
    icon: '⚡',
    difficulty: 5,
    audience: '顶尖竞技玩家 · 空战模拟操控者 · 动态视力最高殿堂挑战者',
    prescription: '每月挑战 1 次，感受在 36 格大变局中处变不惊的高超反应',
    brainTarget: '视网膜到额叶运动区的超高速即时反馈环路重构',
    desc: '36 个密集方格在连续点击中不断发生微调滑动，彻底重置记忆，全凭即刻视野捕捉。',
    targetDuration: '目标: 6×6 动态重排 < 50 秒',
    config: { size: 6, shape: 'grid', mode: 'dynamic_shift', centerFocusDot: false },
    stages: [
      { step: 1, name: '前 12 步建立动感', detail: '适应大盘面微调滑动的规律与节奏' },
      { step: 2, name: '中 12 步敏锐重构', detail: '在方块挪移瞬间重新锁定新方位' },
      { step: 3, name: '后 12 步闪电收盘', detail: '连击突破，达成宏大动态通关' },
    ],
  },

  // =========================================================================
  // 6. 极限耐力与航天高负荷学院 (L89 - L100)
  // =========================================================================
  {
    id: 'plan-089',
    level: 89,
    category: 'endurance',
    title: '7×7 航天员全域超负荷耐力',
    subtitle: '49 阶极限方格 · 考验长达两分钟的高强度意志力',
    tag: '航天员耐力',
    tagColor: 'bg-slate-900 text-amber-300 border-slate-700',
    icon: '🚀',
    difficulty: 5,
    audience: '长跑型耐力选手 · 备考高负荷专业考试 · 需克服注意力中途衰退者',
    prescription: '每周 1-2 次，在精力充沛时进行全神贯注的长效抗衰退训练',
    brainTarget: '持续维持前额叶高浓度供氧，克服后半程神经突触疲劳与注意力涣散',
    desc: '从 1 连续点击至 49，整整 49 个节点。考验不仅是速度，更是绝不松懈的心流定力。',
    targetDuration: '目标: 7×7 用时 < 90 秒',
    config: { size: 7, shape: 'grid', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '前期平稳铺垫', detail: '1-15 保持呼吸平缓，不要盲目冲刺导致提前疲倦' },
      { step: 2, name: '中期抗疲劳期', detail: '16-35 出现视觉疲劳与遗漏时，深呼吸调整焦距' },
      { step: 3, name: '后程意志坚守', detail: '36-49 剩余数字迅速稀疏，果断发起连击收尾' },
    ],
  },
  {
    id: 'plan-090',
    level: 90,
    category: 'endurance',
    title: '7×7 逆水行舟逆向大长征',
    subtitle: '49 倒数至 1 · 长达数十步的持续反向逻辑推演',
    tag: '逆向大长征',
    tagColor: 'bg-amber-100 text-amber-900 border-amber-300',
    icon: '⏳',
    difficulty: 5,
    audience: '需要强化持久高强度逻辑定力 · 克服深度思维惰性者',
    prescription: '每月挑战 1 次，体验长时间反向思考带来的意志升华',
    brainTarget: '长达近百秒的高负荷倒序认知加工，全面拉升心智耐力上限',
    desc: '从 49 连续逆推至 1，49 次逆向判断，绝不允许一秒钟走神。',
    targetDuration: '目标: 7×7 逆序 < 95 秒',
    config: { size: 7, shape: 'grid', mode: 'numbers_desc', centerFocusDot: false },
    stages: [
      { step: 1, name: '大盘面沉着起步', detail: '49-35 稳步推进，建立反向计数心流' },
      { step: 2, name: '中段耐力坚守', detail: '34-15 克服枯燥与眼疲劳，保持匀速' },
      { step: 3, name: '个位数冲刺归零', detail: '14-1 全面爆发，顺利完成大长征' },
    ],
  },
  {
    id: 'plan-091',
    level: 91,
    category: 'endurance',
    title: '7×7 蜂巢错位超域广角搜视',
    subtitle: '49 单元蜂窝六边形 · 超宽非正交视野拉伸',
    tag: '蜂巢超域',
    tagColor: 'bg-purple-100 text-purple-800 border-purple-300',
    icon: '🐝',
    difficulty: 5,
    audience: '欲在超宽广角视野中突破视觉死角极限的高级飞行器驾控人员',
    prescription: '练习时注意放松眼眶周边肌肉，依靠超宽余光大面积覆盖',
    brainTarget: '周边视网膜神经元与丘脑枕核（Pulvinar）的超广角协同调节',
    desc: '49 个六边形蜂窝错位单元铺满视野，消灭一切对角死角，极具视觉冲击力。',
    targetDuration: '目标: 7×7 蜂巢 < 95 秒',
    config: { size: 7, shape: 'honeycomb', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '宏观视野铺展', detail: '注视中心点，让余光向蜂巢四极充分伸展' },
      { step: 2, name: '错位节点平滑跃迁', detail: '目光在倾斜蜂窝间顺畅穿梭' },
      { step: 3, name: '一鼓作气通关', detail: '保持匀称呼吸，顺利完成 49 阶蜂巢挑战' },
    ],
  },
  {
    id: 'plan-092',
    level: 92,
    category: 'endurance',
    title: '7×7 同心圆辐射全景长城',
    subtitle: '49 阶同心圆环 · 径向多层级同心搜寻',
    tag: '同心圆长城',
    tagColor: 'bg-sky-100 text-sky-800 border-sky-300',
    icon: '🌀',
    difficulty: 5,
    audience: '需建立宏大空间视觉辐射扫描模型的海陆空立体搜索专家',
    prescription: '每月 1 次，体验由内向外多圈层辐射的宏大专注心流',
    brainTarget: '顶叶对多重同心极坐标空间网格的深度整合与多尺度解析',
    desc: '同心圆环逐层向外扩张至 49 个节点，径向跨度极大，考验多距离层次的自适应搜寻。',
    targetDuration: '目标: 7×7 同心圆 < 95 秒',
    config: { size: 7, shape: 'circle', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '内核心层快速启动', detail: '先将内圈核心数字迅速点击' },
      { step: 2, name: '中环向外层平滑辐射', detail: '视线向外层圈环平稳扩散' },
      { step: 3, name: '最外环长城收尾', detail: '在巨大外圈圆周上精准锁定收盘' },
    ],
  },
  {
    id: 'plan-093',
    level: 93,
    category: 'endurance',
    title: '7×7 格尔波夫红升黑降极限双轨',
    subtitle: '红1至24升，黑24至1降 · 48步超长双向思维抗疲劳拉锯',
    tag: '红黑超限',
    tagColor: 'bg-rose-900 text-amber-200 border-rose-700',
    icon: '🚀',
    difficulty: 5,
    audience: '追求心智极限抗疲劳能力的特种飞行人员、高级外科医生与特战研究员',
    prescription: '每月挑战 1 次，在长达百秒的高难度双向任务中见证真正的自控力',
    brainTarget: '长达两分钟的双通道工作记忆抗衰退与前额叶能量代谢持续供给',
    desc: '红1-黑24-红2-黑23... 整整48步交替，是心理学界公认的最艰巨注意力分配测验之一。',
    targetDuration: '目标: 7×7 格尔波夫 < 100 秒',
    config: { size: 7, shape: 'grid', mode: 'red_asc_black_desc', centerFocusDot: false },
    stages: [
      { step: 1, name: '稳健布局双轨', detail: '红升与黑降从两端沉着起跑' },
      { step: 2, name: '顶住中段混淆风暴', detail: '数值接近时杜绝串轨，保持呼吸均匀' },
      { step: 3, name: '坚毅撞线完成', detail: '两路人马背向归位，圆满通关' },
    ],
  },
  {
    id: 'plan-094',
    level: 94,
    category: 'endurance',
    title: '7×7 千字文国风宏编长卷',
    subtitle: '49 个汉字全篇连贯搜寻 · 领略国风文学速读最高峰',
    tag: '千字宏卷',
    tagColor: 'bg-emerald-900 text-amber-200 border-emerald-700',
    icon: '📖',
    difficulty: 5,
    audience: '高阶国学速读大家 · 欲挑战一目十行超大视野阅读的高手',
    prescription: '每月 1 次，在 49 个汉字的浩瀚卷轴中体验身心合一的专注入定',
    brainTarget: '大规模汉字图像整体摄入中枢的高负荷连续运转',
    desc: '由天地玄黄至露结为霜、金生丽水，49 个经典千字文汉字铺满全屏，极具国风美感。',
    targetDuration: '目标: 7×7 千字文 < 90 秒',
    config: { size: 7, shape: 'grid', mode: 'chinese_chars', centerFocusDot: false },
    stages: [
      { step: 1, name: '天地玄黄开卷', detail: '顺应千古名篇气势沉着起步' },
      { step: 2, name: '日月盈昃中程巡礼', detail: '在大盘面上整体把握字形特征' },
      { step: 3, name: '金生丽水通达收官', detail: '点毕最后一个汉字，气魄浑然天成' },
    ],
  },
  {
    id: 'plan-095',
    level: 95,
    category: 'endurance',
    title: '8×8 视觉极限六十四卦象大域',
    subtitle: '64 阶广域方阵 · 视网膜广角视野的极致洗礼',
    tag: '64阶广域',
    tagColor: 'bg-slate-950 text-sky-300 border-slate-800',
    icon: '🔭',
    difficulty: 5,
    audience: '专业视觉耐力运动员 · 追求广域视野探索极致的极客',
    prescription: '每月 1-2 次，保持视线平缓，体验 64 格方阵尽收眼底的浩瀚感',
    brainTarget: '视网膜外围杆状细胞与中央凹锥状细胞的大尺度协同作业',
    desc: '整整 64 个方格！如同周易六十四卦的大天地，考验从微观到宏观的全域视野驾驭力。',
    targetDuration: '目标: 8×8 用时 < 130 秒',
    config: { size: 8, shape: 'grid', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '1-20 稳健起跑', detail: '保持大局观，不因个别数字短暂卡顿而急躁' },
      { step: 2, name: '21-45 沉着巡航', detail: '余光分区排查，保持连贯的呼吸节拍' },
      { step: 3, name: '46-64 冲刺破关', detail: '剩余目标迅速稀疏，果断发起连击通关' },
    ],
  },
  {
    id: 'plan-096',
    level: 96,
    category: 'endurance',
    title: '8×8 逆向倒数长空远征',
    subtitle: '64 递减倒数至 1 · 挑战高负荷逆向逻辑马拉松',
    tag: '长空远征',
    tagColor: 'bg-amber-950 text-amber-200 border-amber-800',
    icon: '⏳',
    difficulty: 5,
    audience: '高阶意志力磨砺者 · 需进行超长周期抗疲劳战略决策者',
    prescription: '精力充沛时挑战 1 次，磨炼百折不挠的逆向神经定力',
    brainTarget: '前额叶背外侧皮质在超长周期下的反向思维抑制控制稳定性',
    desc: '从 64 连续倒退直至 1，64 步反向推演，是对思维耐受力与自控力的深度磨炼。',
    targetDuration: '目标: 8×8 逆序 < 140 秒',
    config: { size: 8, shape: 'grid', mode: 'numbers_desc', centerFocusDot: false },
    stages: [
      { step: 1, name: '64-45 高原起步', detail: '稳住逆序倒数的心理心流' },
      { step: 2, name: '44-20 穿越迷宫', detail: '跨越多个整十位，保持推导平顺' },
      { step: 3, name: '19-1 极速归零', detail: '顺利撞线归零，完成远征' },
    ],
  },
  {
    id: 'plan-097',
    level: 97,
    category: 'endurance',
    title: '8×8 蜂巢错位超长心流探索',
    subtitle: '64 蜂窝单元 · 非正交几何结构下的超长专注心流',
    tag: '蜂巢巨阵',
    tagColor: 'bg-purple-950 text-purple-200 border-purple-800',
    icon: '🐝',
    difficulty: 5,
    audience: '复杂拓扑视觉探索者 · 追求宏大非线性专注心流的高级极客',
    prescription: '每月 1 次，沉浸在六边形蜂窝巨阵带来的奇妙心流中',
    brainTarget: '非线性空间网格编码系统在超大负荷下的自适应整合',
    desc: '64 个错位蜂窝节点，兼具广度与复杂的倾斜交错几何，视觉探索的极致体验。',
    targetDuration: '目标: 8×8 蜂巢 < 140 秒',
    config: { size: 8, shape: 'honeycomb', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '建立全局蜂窝感', detail: '将视线放开，拥抱全景蜂巢' },
      { step: 2, name: '斜向高效联结', detail: '利用蜂窝斜向节点高效扫视' },
      { step: 3, name: '宏大通关', detail: '完成 64 蜂巢巨阵挑战' },
    ],
  },
  {
    id: 'plan-098',
    level: 98,
    category: 'endurance',
    title: '8×8 斯特鲁普色彩抗扰终极长城',
    subtitle: '64 格字色剧烈矛盾 · 挑战长时间抗诱导决策意志',
    tag: '终极抗扰',
    tagColor: 'bg-rose-950 text-rose-200 border-rose-800',
    icon: '🎨',
    difficulty: 5,
    audience: '高难度心理学测试挑战者 · 需在复杂信息轰炸中保持清醒的高级决策人',
    prescription: '每月挑战 1 次，在 64 次色彩冲突中保持绝对的冷眼旁观',
    brainTarget: '前扣带回皮层对长达两分钟以上连续诱导干扰的绝对阻断',
    desc: '64 个方格充满字义与色彩矛盾，在长时间大盘面下连续做出正确颜色决断，意志坚如磐石。',
    targetDuration: '目标: 8×8 斯特鲁普零失误 < 140 秒',
    config: { size: 8, shape: 'grid', mode: 'stroop_color', centerFocusDot: true },
    stages: [
      { step: 1, name: '稳固色彩防火墙', detail: '前 20 项确立只认颜色的绝对准则' },
      { step: 2, name: '中途严防视觉疲劳', detail: '21-45 项深呼吸，克服眼疲劳欺骗' },
      { step: 3, name: '坚不可摧完赛', detail: '以 100% 极高准确率终结比赛' },
    ],
  },
  {
    id: 'plan-099',
    level: 99,
    category: 'endurance',
    title: '9×9 九九归一全域天王山',
    subtitle: '81 阶殿堂级方格 · 视网膜与大脑算力的最高礼赞',
    tag: '九九归一',
    tagColor: 'bg-slate-950 text-amber-300 border-amber-500/50 shadow-sm',
    icon: '👑',
    difficulty: 5,
    audience: '专注力大师 · 欲登顶舒尔特方格金字塔顶峰的终极挑战者',
    prescription: '每季度挑战 1 次，作为个人专注力与意志力登峰造极的终极检阅',
    brainTarget: '全脑视觉、注意、执行与心智耐受力各大网络的巅峰集成运作',
    desc: '整整 81 个数字！九九八十一难，终成正果。考验人类专注力的终极天王山。',
    targetDuration: '目标: 9×9 终极挑战 < 180 秒',
    config: { size: 9, shape: 'grid', mode: 'numbers_asc', centerFocusDot: true },
    stages: [
      { step: 1, name: '1-25 筑基沉着', detail: '平心静气起步，将 81 格视作辽阔星辰大海' },
      { step: 2, name: '26-55 穿云破雾', detail: '中程最艰难处保持呼吸，稳扎稳打分区扫视' },
      { step: 3, name: '56-81 登顶飞升', detail: '剩余数字一目了然，以澎湃连击完成登顶' },
    ],
  },
  {
    id: 'plan-100',
    level: 100,
    category: 'endurance',
    title: '9×9 逆水行舟终极大圆满',
    subtitle: '81 阶倒序 81→1 · 舒尔特专注力与意志力最高殿堂',
    tag: '终极大圆满',
    tagColor: 'bg-gradient-to-r from-amber-900 via-slate-900 to-amber-900 text-amber-200 border-amber-500',
    icon: '🏆',
    difficulty: 5,
    audience: '专注力殿堂级宗师 · 挑战人类脑力自控极限的终极修行者',
    prescription: '登顶之作，在最宁静专注的时刻向自我极限发起庄严挑战',
    brainTarget: '前额叶认知控制网络长时程高强度无断点巅峰心流输出',
    desc: '由 81 逆向倒退至 1，81 阶大长征。至此，全套 100 种科学专注力训练方案达成终极大圆满！',
    targetDuration: '目标: 9×9 终极逆序 < 195 秒',
    config: { size: 9, shape: 'grid', mode: 'numbers_desc', centerFocusDot: false },
    stages: [
      { step: 1, name: '81-55 天河倒流', detail: '从 81 沉稳起势，反向逆流而上' },
      { step: 2, name: '54-25 万壑归川', detail: '中段克服深层脑疲劳，保持如冰雪般的清明' },
      { step: 3, name: '24-1 极速归真', detail: '点中最后数字 1，心流圆满，达成第 100 关传奇！' },
    ],
  },
];
